### ISSUE TITLE
Progress bar in list column not visible

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#1000]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

None

### Issue description

When using progress bar in list's column, the bar does not have visible height.  

The progress bar height is set to `auto` by [`table.table.data tbody th div.progress` rule](https://github.com/wintercms/winter/blob/develop/modules/system/assets/ui/storm.css#L3166)
https://github.com/wintercms/winter/blob/05000d2663b7bd1c7bc2272352ea932bc915ea97/modules/system/assets/ui/storm.css#L3166

**Screenshot of the different heights with progress bar progression set to 60%:**    

![image](https://github.com/wintercms/winter/assets/282242/bc529792-def8-4998-b32b-68f3004dcdff)
a border was added to best view the progress bar.

This issue was seen with Firefox, need confirmation on other browsers.

### Steps to replicate

Set a list's column to `type: partial` with [markup as defined in UI docs](https://wintercms.com/docs/v1.2/ui/style/progressbar).

### Workaround

Maybe set `table.table.data tbody th div.progress` height to use either a minimal height or make use of a css variable with a default fallback (`height: var(--progress-height, 9px)`).

In the second case, we can set the progress bar height by defining a value in our partial : 
```html
<div class="progress" style="--progress-height: 18px;">
    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
        <span class="sr-only">60% Complete</span>
    </div>
</div>
```

**Comment by bennothommo** [comment]
@damsfx I'd be happy for a minimum height to be enforced on progress bars in the list, as long as it is the same height as the text size by default.

**Comment by damsfx** [comment]
> @damsfx I'd be happy for a minimum height to be enforced on progress bars in the list, as long as it is the same height as the text size by default.

@bennothommo  The cell font-size is 13px while the cell line-height is 18.5667px.  
I guess it would be better to fit line-height, rounded lower: 18px.  

What do you think about using a css variable?  
This allow user to define his own height in partial.
