### ISSUE TITLE
Flash message has no style in cms theme

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#1003]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Hi,

I'm trying to display a success flash message but apparently the classes `alert` and `alert-success` do not exist. I'm following this [documentation](https://wintercms.com/docs/v1.2/markup/tags/flash). How can I include these classes? Thank you.

### Steps to replicate

https://wintercms.com/docs/v1.2/markup/tags/flash

**Comment by arvislacis** [comment]
@goldmont I believe documentation is referencing to Bootstrap styling (https://getbootstrap.com/docs/5.2/components/alerts/). If you are not using Bootstrap or other CSS framework which has these styles then you can define styles with your own CSS.

**Comment by goldmont** [comment]
> @goldmont I believe documentation is referencing to Bootstrap styling (https://getbootstrap.com/docs/5.2/components/alerts/). If you are not using Bootstrap or other CSS framework which has these styles then you can define styles with your own CSS.

Understanding, in fact I'm using TailwindCSS. I thought these were internal classes. Thank you.
