### ISSUE TITLE
Old October CMS branding in Mail Settings

### ISSUE THREAD

**Issue by nathanlesage** [wintercms/winter#1010]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Blog, Winter.Pages, Indikator.Backend, JanVince.SmallRecords, Winter.Sitemap

### Issue description

When going into the backend to "Settings" -> "Mail Branding", you will see that above the partial templates as well as below, there is still "October CMS" written there. I tried to find where these strings come from, but I couldn't find them, so I'm opening an issue instead of a PR.

### Steps to replicate

See the screenshot:

![image](https://github.com/wintercms/winter/assets/17251683/0b6f7a4a-adc1-4093-86b9-78bb87a1e7f7)

**Comment by nathanlesage** [comment]
Addendum: This was formerly an October CMS instance, so there is a chance that this could've come from the cache, but I have cleared the cache several times, and I couldn't fix this issue.

**Comment by AIC-BV** [comment]
@nathanlesage I think you have to set the 'name' property in config/app.php

**Comment by nathanlesage** [comment]
Oh my, I'm an idiot. I forgot about this setting; there are too many places where you can set the application name 😵‍💫

**Comment by LukeTowers** [comment]
To be fair, that value should be pulling from the app name set in the backend. Did you have a custom app name set in the backend branding settings already @nathanlesage? If you did then I'd consider it a bug for the mail template to not be using that value.

**Comment by nathanlesage** [comment]
Yup, I have adapted the entire backend. This was also what threw me off, because I looked at the app title first, and saw that I inserted the correct one there. That was why I had no idea where this was coming from.

**Comment by LukeTowers** [comment]
@nathanlesage are you able to submit a PR to adjust that to pull from the BrandSettings model instead of the configuration value directly?

**Comment by nathanlesage** [comment]
@LukeTowers I would love to, but right now I'm swamped with work both on Zettlr and on my PhD, so I can't promise any timeline – I would have to dig a bit into the code, since I'm still a tad unsure how the various parts interact in WinterCMS :/
