### ISSUE TITLE
Deprecated warning when using tinker to access a model file

### ISSUE THREAD

**Issue by fanti1** [wintercms/winter#1015]
### Winter CMS Build

1.2

### PHP Version

Other (please specify below)

### Database engine

MySQL/MariaDB

### Issue description

A warning message with the word DEPRECATED appears when I use tinker to access a file within a model.
![image](https://github.com/wintercms/winter/assets/23063442/a4a30250-b60c-4859-91e9-e42b79ee0556)

### Steps to replicate

1 - Attach an image inside any model using $attachOne as shown in https://wintercms.com/docs/v1.2/docs/database/attachments#file-attachments
2 - Using tinker, access the model like the example in the image above
```
use Model;
$a = Model::find(1);
$a->key_from_attachone
```
And the message probably will show up.

Im using PHP version 8.2.11.

**Comment by mjauvin** [comment]
Fixed by https://github.com/wintercms/storm/pull/165
