### ISSUE TITLE
Add MigrationHelper for plugin replacement functionality

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#102]
The plugin replacement functionality is nearly perfect, but maintaining data integrity is still a bit tricky. It would be ideal if we had a MigrationHelper that could do the following:

- Rename Settings model's codes (this could potentially be done at the core level with aliases, or we could just not rename these in the first place)
- Iterate over all models in the plugin & all of their relationships that store class information in the database (i.e. attachOne, attachMany, morphOne, morphMany, all when not using a morph map) and run migrations to migrate the data in the database to support the new class names. 

Ideally this helper would also support being run in reverse.

>**NOTE:** We could also explore the idea of having Laravel replace these values at the query level seeing as it's highly likely that other plugins could be extending the replaced plugins and referencing those models in their own data structure.

Plugins that should at the very least have manual migrations added to them prior to 1.1.3 being launched:

- [x] Winter.Blog
- [x] Winter.Builder
- [x] Winter.GoogleAnalytics
- [x] Winter.Mailchimp
- [x] Winter.Twitter
- [x] Winter.User

**Comment by mjauvin** [comment]
@LukeTowers those stored classes in the db tables, wouldn't they get remaped when used as well?

**Comment by LukeTowers** [comment]
@mjauvin no, $settings->file is going to look for `system_files where field = file, attachment_type = New\Classe, attachment_id = $id` whereas any existing data is going to be stored as `Old\Class`.

**Comment by mjauvin** [comment]
Indeed.

**Comment by LukeTowers** [comment]
Finished through the inclusion of migrations in the affected plugins to handle these tasks.
