### ISSUE TITLE
Wintercms 1.24 update

### ISSUE THREAD

**Issue by Artful-dodger** [wintercms/winter#1034]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Plugin install button

### Issue description

I have installes the latest wintercms 1.24 on my server every thing seems to work but the themes install button and the plugin install but I get this error "TypeError: Winter\Storm\Network\Http::data(): Argument #2 ($value) must be of type ?string, array given, called in" I have installed it on a nginx server which is version 1.22 not sure why or how to solve

### Steps to replicate

Installed wintercms on debian 12 lemp server with new config for nginx

**Comment by Artful-dodger** [comment]
Hi mjauvin any work arounds for this till the release of 1.2.5

**Comment by mjauvin** [comment]
Other than monkey patching this, no.

**Comment by Artful-dodger** [comment]
manual install of plugins it is then

**Comment by LukeTowers** [comment]
You can switch to the develop branch until the end of the month when we'll release 1.2.5
