### ISSUE TITLE
[Frontend] Lang support with file

### ISSUE THREAD

**Issue by m-paniez9292** [wintercms/winter#1037]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Translate

### Issue description

Hi,
I work with a fresh install of Wintercms.
I would like to use lang file for my theme and I follow steps at the end of your doc page : https://wintercms.com/docs/v1.2/docs/themes/development#localization-directory-and-file-structure
So, I create a directory lang in my theme directory (ie. themes > foo > lang > en > lang.php) and, in my theme, in a partial file, I put `{{'themes.foo::lang.global.bar'|trans}}` but it doesn't work (I try without trans filter, but the same).
How can I do that ?
Thanks

### Steps to replicate

A fresh install of wintercms + Winter.Translate plugin and follow https://wintercms.com/docs/v1.2/docs/themes/development#localization-directory-and-file-structure

**Comment by AIC-BV** [comment]
What if you don't use |trans?

**Comment by AIC-BV** [comment]
I don't think you can use that method of translation on the frontend
<img width="565" alt="image" src="https://github.com/wintercms/winter/assets/89913092/784d6b97-eb13-4a21-b5bd-ada9363c00c1">
https://github.com/wintercms/wn-translate-plugin
Typically, you can do `{{ 'Hello world' |_ }}` in your main website language and translate it in the backend at settings (doesn't need primary language translation). You could also do `{{ 'site.introduction' |_ }}` and translate that key for every language.

You can also use theme.yaml to define keys and translations like you wanted, but I haven't personally used that yet. Using theme.yaml makes it difficult for other people that don't know code to translate strings

**Comment by m-paniez9292** [comment]
Re,
Yes, I know that part.
But, I think, it's better to have lang file system for standard/repetetive frontend text part. There are always "phone", name", "contact", ... terms in any website and I would like 1 file to put translation and never come back about that.
So, the lang file systems, like plugin but for a theme, is a better way than redo same translations every time.
Thanks

**Comment by AIC-BV** [comment]
In that case I would personally use theme.yaml (as explained on the [wn-translate-plugin](https://github.com/wintercms/wn-translate-plugin)), or create your own simple 'settings' plugin like so, which I find a little more flexible than theme.yaml but takes a little bit more effort to set up

1. Create folder at plugins/author/mypluginname
2. Create Plugin.php in that folder
```
<?php namespace Author\MyPluginName;
use System\Classes\PluginBase;

use Event;
use Author\MyPluginName\Models\Settings;

class Plugin extends PluginBase {

    public function registerSettings()
    {
        return [
            'settings' => [
                'category'    => 'My title',
                'label'       => 'Global settings',
                'description' => "Manage variables like logos, favicons, contact information and more.",
                'icon'        => 'icon-cogs',
                'class'       => 'Author\MyPluginName\Models\Settings',
            ]
        ];
    }
}

public function boot()
{
      // You can now access {{ settings }} in the layouts
      Event::listen('cms.page.beforeDisplay', function($controller, $url, $page) {
          $controller->vars['settings'] = Settings::instance();
      });
}
```
3. Create settings model at plugins/author/mypluginname/models/Settings.php
```
<?php namespace Author\MyPluginName\Models;
use Model;

class Settings extends Model
{
    
    public $implement = ['@Winter.Translate.Behaviors.TranslatableModel', '@System.Behaviors.SettingsModel'];
    public $settingsCode = 'author_global_settings';
    public $settingsFields = 'fields.yaml';

    public $translatable = [
        'website_name',
        'default_meta_title',
        'default_meta_description',
        'default_og_title',
        'default_og_description',
        'default_og_image',
        'street',
        'city',
        'phone',
        'contact_time',
        'contact_time_short',
        'cookie_title',
        'cookie_accept',
        'cookie_description',
        'cookie_info',
        'thank_you',
        'success_tooltip',
        'required_error',
        'email_error',
        'vat_placeholder',
        'delivery_countries',
        ...
    ];

}
```
4. Create settings fields.yaml at at plugins/author/mypluginname/models/settings/fields.yaml
5. Fill in and translate at your backend settings

And now you can use `{{ settings.website_name }}` in the frontend

**Comment by damsfx** [comment]
In your `theme.yaml` (/themes/acme/theme.yaml) file, you could define the translation files : 
```yaml
translate:
    fr: lang/fr.yaml
    en: lang/en.yaml
    de: lang/de.yaml
```

In each translation file, you have to define keys/values translations : 
```yaml
# FR file /themes/acme/lang/fr.yaml
index.news: 'Actualités'

# EN file /themes/acme/lang/en.yaml
index.news: 'News'
```
And in your pages/partials use `{{ 'index.news' | _ }}`.
>Translating frontend content should be handled with the [Winter.Translate](https://github.com/wintercms/wn-translate-plugin) plugin.

**Comment by m-paniez9292** [comment]
Re,
Sorry @AIC-BV , I did this "method" before, but, for me, it's a hack and not a method.
And I search a method like @damsfx . But, it doesn't work :
- I follow points and I can see "translations var" in bacckend > settings > Translate message (so, I think theme.yaml point and lang file are ok)
- but I don't see translated message, I see only the "translations var" (ie. index.news in the example) : are you sure about `{{ 'index.news' | _ }}` ?

Thanks

**Comment by mjauvin** [comment]
> Re, Sorry @AIC-BV , I did this "method" before, but, for me, it's a hack and not a method. And I search a method like @damsfx . But, it doesn't work :
> 
> * I follow points and I can see "translations var" in bacckend > settings > Translate message (so, I think theme.yaml point and lang file are ok)
> * but I don't see translated message, I see only the "translations var" (ie. index.news in the example) : are you sure about `{{ 'index.news' | _ }}` ?
> 
> Thanks

That works, but needs `wn-translate-plugin`.

**Comment by m-paniez9292** [comment]
Re,
Yes, I have it (to see translation part in backend, I need this plugin).

![Capture d’écran du 2024-01-17 15-03-05](https://github.com/wintercms/winter/assets/17120690/e04d9c1d-8d1a-42cd-bdde-90bf2be3c441)

As you can see, in this example, I see my translate var contact.has_copy (contact.has_copy is in my lang/fr.yaml file) and its translated value. But, it doesn't display on the front, I have contact.has_copy.


Thanks

**Comment by m-paniez9292** [comment]
Re,

Ok, I try with other translated var and it works perfectly, but not this one (i will search).

EDIT : Don't forget to click on "Clear cache" in backend > Settings > Translate messages, on the top of the page ;-)

So thanks for your help.
