### ISSUE TITLE
Schema forced after successful backend sign-in

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#1051]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Hi,

Apparently WinterCMS forces schema and port after a successful backend sign-in ignoring `app.url` value despite `cms.linkPolicy` is set to `force`. In the browser network tab I see that the sign-in request is sent correctly to the `app.url` but then the backend responds with a `302 Redirect` cutting off my custom port. Thus the backend becomes unreachable and I have to enter manually the port in the browser url bar. Then I can navigate with no problem. I think that there is some problem with [this](https://github.com/wintercms/wn-backend-module/blob/6b496a3d49badffc797b997570923b2d8c19a371/controllers/Auth.php#L108) line inside the `Auth` controller.

### Steps to replicate

1. Specify a custom port in `app.url`. E.g.: https://example.com:10443
2. Sign-in into the backend.

### Workaround

Enter manually the custom port in the browser url bar after a successful sign-in.

**Comment by LukeTowers** [comment]
@goldmont are you able to throw a `dd()` on that line to see if the generated redirect response includes the port or not? If it doesn't then we should fix that.
