### ISSUE TITLE
updates plugin/theme under updates & plugins, got an exception  

### ISSUE THREAD

**Issue by mavrik74** [wintercms/winter#1054]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Winter\Storm\Network\Http::data(): Argument #2 ($value) must be of type ?string, array given, called in /home/mono/web/=================/vendor/winter/storm/src/Network/Http.php on line 469

### Steps to replicate

Go to updates plugin/theme under updates & plugins, got an exception

**Comment by mjauvin** [comment]
Duplicate of #1034
