### ISSUE TITLE
Named routes not working

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#106]
- Winter CMS Build: 18adc4a12d886d36ce396f6be4f1732e8b40d062
- PHP Version: 7.4
- Database Engine: sqlite
- Plugins Installed:
  * Winter.Demo

### Description:
When registering named routes in a plugin's routes.php file you are unable to reference them using the `route()` helper function. However, they do show up in the route list when running `php artisan route:list`

### Steps To Reproduce:
1. Create custom plugin
2. Create routes.php file with a named route:
```php
Route::get('sitemap.xml', [\Radmin\Client\Classes\Http\Controllers\SitemapController::class, 'index'])
    ->middleware(['web'])
    ->name('sitemap');
```
3. Create a component which references that named route: `route('sitemap')`
```php
<?php namespace Radmin\Client\Components;

use Cms\Classes\ComponentBase;

class Sitemap extends ComponentBase
{
    public string $url;

    public function componentDetails()
    {
        return [
            'name'        => 'Sitemap Component',
            'description' => 'No description provided yet...'
        ];
    }

    public function defineProperties()
    {
        return [];
    }

    public function onRender()
    {
        $this->url = route('sitemap');
    }
}

```

routes list:
```
+--------+----------+-------------+---------+----------------------------------------------------------------+------------+
| Domain | Method   | URI         | Name    | Action                                                         | Middleware |
+--------+----------+-------------+---------+----------------------------------------------------------------+------------+
|        | GET|HEAD | sitemap.xml | sitemap | Radmin\Client\Classes\Http\Controllers\SitemapController@index | web        |
+--------+----------+-------------+---------+----------------------------------------------------------------+------------+
```

![Screenshot from 2021-04-23 09-49-34](https://user-images.githubusercontent.com/63664924/115889111-44c79400-a419-11eb-8ce6-fcb4b1c70acb.png)

**Comment by LukeTowers** [comment]
Found the issue, pushing a fix: https://stackoverflow.com/questions/42984295/laravel-named-routes-not-working/67258851#67258851
