### ISSUE TITLE
Error when trying to install plugin in a fresh install

### ISSUE THREAD

**Issue by rborcherds** [wintercms/winter#1067]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When I use the web backend interface to install a plugin, I get this error

"Attempt to read property "created_at" on null" on line 1048 of ......../modules/system/classes/UpdateManager.php

### Steps to replicate

Go to the Updates & Plugins page and click on any of the these buttons at the top of the page:

Check for Update
Install Plugins
Install Themes

### Workaround

Use composer at the command prompt to install the plugins. I have not found a workaround in the web interface.

**Comment by bennothommo** [comment]
@borcherds-ralph Composer is currently the only way truly supported in Winter for installing plugins and themes.

**Comment by LukeTowers** [comment]
This particular error has been reported many times, it was introduced in 1.2.4 and has already been fixed on develop.
