### ISSUE TITLE
Missing Storage facade

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#1068]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

none

### Issue description

Running latest WinterCMS version (dev-develop d5fd520), when calling `php artisan winter:util` command throw an error : 
`In WinterUtil.php line 309:
  Class "System\Console\Storage" not found`

The commit #934 commit is behind this error.

### Steps to replicate

Install the latest version of WinterCMS and call one of the commands `php artisan winter:util`.

**Comment by mjauvin** [comment]
Confirmed. The referenced PR resolves the issue.
