### ISSUE TITLE
Issues with PHP 8.3

### ISSUE THREAD

**Issue by rborcherds** [wintercms/winter#1075]
### Winter CMS Build

1.2

### PHP Version

Other (please specify below)

### Database engine

MySQL/MariaDB

### Plugins installed

any plugin

### Issue description

When you use composer to install a plugin that has a database table with it and then run the php artisan migrate script, the migration script does not run for the plugin.

In the Updates & Plugins page with PHP 8.3 you do not get that updated with the plugins you have installed with composer.

When you run the artisan migrate command you get this message with PHP 8.3

In VersionManager.php line 360:
                                                                                           
  Increment on type bool has no effect, this will change in the next major version of PHP 

### Steps to replicate

Make sure you are running PHP 8.3.  
Fresh install of WinterCMS 1.2.4

### Workaround

Downgrade PHP to 8.2 and everything seems to work with the plugins showing in Updates & Plugin page and the migrations for the plugins work and the database tables are created.

**Comment by LukeTowers** [comment]
This has been fixed on develop. We will be releasing the next version shortly. Thanks!
