### ISSUE TITLE
Error when click "Install plugins" and "install themes" button in wintercms's admin page

### ISSUE THREAD

**Issue by BuiLuan1989-vns** [wintercms/winter#1081]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

After install Winter cms on local environment, I try to install plugins and themes from admin page but it get error when i click on button.
Environments:
  Windows 10
  Laragon server
  PHP 8.1
  Mysql 8

### Steps to replicate

1. Install winter cms with composer (use environment of paragon)
2. login to winter backend
3. Click install plugins and install themes

**Comment by damsfx** [comment]
Same as #1067 #1054 #1050 #1034

Composer is currently the only way truly supported in Winter for installing plugins and themes.

**Comment by LukeTowers** [comment]
Alright alright, I'll push out a new update already 😜
