### ISSUE TITLE
Count parameter not working with Has-Many-Through relation

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#1086]
### Winter CMS Build

1.2.5

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Hi,

I have the following scenario: a `Project` has **only one** `Board` which has many `Tasks`. I would like to get the count of all tasks belonging to a project. It's like WinterCMS is ignoring the `count` parameter because what I get is an array of `Task` models.

`Project` model:
```php
public $hasManyThrough = [
	'tasks_count' => [
		Task::class,
		'through' => Board::class,
		'key' => 'project_id',
		'throughKey' => 'board_id',
		'scope' => 'completed',
		'count' => true,
	]
];
```

The scope `completed` is ignored too.

`Task` model:
```php
public function scopeCompleted($query)
{
	return $query->where('status', TaskStatus::Completed);
}
```

### Steps to replicate

Set up a `Has-Many-Through` relation and try to get the `count`.

### Workaround

I had to set up the `Has-Many-Through` relation without `count` and `scope` parameters and then use `$appends` to insert the count value into the response.

`Project` model:
```php
public $appends = [
	'tasks_completed_count'
];

public $hasManyThrough = [
	'tasks' => [
		Task::class,
		'through' => Board::class,
		'key' => 'project_id',
		'throughKey' => 'board_id'
	]
];

public function getTasksCompletedCountAttribute()
{
	return $this->tasks()->completed()->count();
}
```

**Comment by mjauvin** [comment]
@goldmont is the `scope` relation parameter working without the `count` parameter present or not ?

**Comment by goldmont** [comment]
> @goldmont is the `scope` relation parameter working without the `count` parameter present or not ?

Yes, of course it works.

EDIT:
@mjauvin I mean the scope. I haven't tested the `scope` parameter alone. I'll let you know later this evening.

**Comment by goldmont** [comment]
@mjauvin I made some tests with the `scope` parameter alone but no luck. The `Has-Many-Through` relation returns all the results.

**Comment by mjauvin** [comment]
Yeah, I'm working on a fix right now...

**Comment by goldmont** [comment]
Thank you for your efforts @mjauvin
