### ISSUE TITLE
Fontawesome 6.1.1 to 6.5.1 for remove Font console error

### ISSUE THREAD

**Issue by willouch** [wintercms/winter#1090]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

In Backend, Fontawesome cause error message.
Up to Fontawesome 6.5.1 resolve Font console error :
`downloadable font: Glyph bbox was incorrect (glyph ids 5 9 10 12 13 15 16 33 49 59 60 61 72 76 81 83 84 85 88 91 92 97 101 102 103 104 106 107 109 118 120 121 122 124 134 135 136 137 139 141 143 145 146) (font-family: "Font Awesome 6 Free" style:normal weight:300 stretch:100 src index:0) source: /webfonts/xxxxxxx.woff2`

### Steps to replicate

Font Error message in logs browser console from Backend

**Comment by arvislacis** [comment]
This is FontAwesome issue happening in Firefox browser: https://github.com/FortAwesome/Font-Awesome/issues/19925

Nothing critical but updating font files to FontAwesome 6.5.1 version will fix this.

**Comment by LukeTowers** [comment]
PR welcome :)
