### ISSUE TITLE
Broken default email layout after upgrading to Twig 3.9.1

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#1103]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Hi,

After upgrading to Twig 3.9.1 from 3.8.0, I noticed that the footer in the default email layout is broken. The title too.

Before upgrade:
![image](https://github.com/wintercms/winter/assets/6855692/33b03ab5-6c6d-4579-99c8-ef937b9aac49)

After:
![image](https://github.com/wintercms/winter/assets/6855692/5e556885-68f2-4ef6-8e59-5743d4dbc1cf)

I made no changes to the email layout. What could be the problem?

The email partial is the following:
```twig
==
<p>{{ content }}</p>
{% if additional_data is not empty %}
    <p>Informazioni aggiuntive:<br>{{ additional_data }}</p>
{% endif %}
```

Thanks.

### Steps to replicate

Read above

**Comment by josephcrowell** [comment]
The maintenance team is aware. 
See these:
https://github.com/wintercms/storm/commit/faf49137344e9bff44b995adb35ff0a7633e7d65
https://github.com/wintercms/winter/commit/d9eaf58eacaf821471779caa7e9833846caacd38
https://github.com/wintercms/winter/pull/1102

**Comment by LukeTowers** [comment]
For now just lock your twig version to 3.8
