### ISSUE TITLE
Image not upload

### ISSUE THREAD

**Issue by wemaster5** [wintercms/winter#1118]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

i am trying to upload image but i am having a issue with that.
![Screenshot_118](https://github.com/wintercms/winter/assets/159421877/4c694869-8f20-42c0-87f9-937ea1f506e7)

### Steps to replicate

just entered to default page to add some image and that happend , dont have any error on logs

**Comment by LukeTowers** [comment]
Did you check your browser's developer console and network tab for reported issues?

**Comment by wemaster5** [comment]
![Screenshot_120](https://github.com/wintercms/winter/assets/159421877/a8aa175d-b334-4cf6-ac57-a13f1dfcfe7d)
here i am on localhost and i have installed by download not by composer . 
Even i server i have the same problem

**Comment by LukeTowers** [comment]
Are you using a public folder? Do those files actually exist locally?

**Comment by wemaster5** [comment]
yes they exist , even i try to show after i upload on media folder i have same error.
Same happen even when i try to add pictures by drag & drop

**Comment by LukeTowers** [comment]
Without knowing more about your hosting setup (server software, file permissions, CDN, etc) I can't help you further. If you'd like to schedule a call with me where we can go over the issue and I can provide live support then shoot me a message on Discord or send me an email.

**Comment by wemaster5** [comment]
sure i will write you in linkedin

**Comment by bennothommo** [comment]
Closing this for now as there's been no follow-up. If the issue persists, please get in touch and we'll investigate further.
