### ISSUE TITLE
Builder Plugin does not install

### ISSUE THREAD

**Issue by bkrajendra** [wintercms/winter#112]
It's great to see the origin of Winter after leaving back October!!! 😁

I gave it a try today because everything went very well, and I liked the CLI install interface. 
Only I got an error while installing the Builder plugin through the CLI install menu but showed me 520 origin error.

I also suggest having a marketplace completely based on GitHub. 
Is there any way we can directly clone plugins using GitHub API or any other way from PHP and install them in winter.
Not sure if I am sounding meaningful, but I don't like the idea of having a marketplace server, as someone has to maintain it and if something like October happens then there is no way anyone can depend on it.

**Comment by LukeTowers** [comment]
You should now be able to search for and install Winter.Builder from the backend of your Winter CMS projects and the CLI.
