### ISSUE TITLE
Upgrade wikimedia/minify to the latest version

### ISSUE THREAD

**Issue by austinderrick** [wintercms/winter#1158]
Is there a reason we still use version 2.2 of wikimedia/minify?

It is currently breaking in a weird spot with one of our combined files, causing JavaScript errors.
It appears that the newest version (2.7) does not have this issue.

https://github.com/wintercms/storm/blob/develop/composer.json#L51C9-L51C36
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/libs/Minify/+/refs/tags/2.7.0

**Comment by LukeTowers** [comment]
@austinderrick no, that's just the base version that we require. Composer should be pulling in the latest version that meets those requirements (i.e. `2.*`).

What does `composer show wikimedia/minify` return for you?

**Comment by austinderrick** [comment]
Ah, oops! I misread that composer file.

Thanks for the clarification. Upon further investigation, the fix I'm looking for is an unreleased fix in the vendor repo.
