### ISSUE TITLE
Backend list tree view unable to expand from second level on

### ISSUE THREAD

**Issue by goldmont** [wintercms/winter#1160]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Hi,

I'm not able to expand tree view records from second level on. I can successfully expand the root level but I'm not able to see the children of the first child.

![image](https://github.com/wintercms/winter/assets/6855692/d72c3640-9346-44f2-984c-c6af082ada46)

When I try to expand the record with ID `2`, the page is simply refreshed and the whole tree collapsed:
![ezgif-6-08d3865357](https://github.com/wintercms/winter/assets/6855692/482ac54d-c2fd-4ca6-9390-7bca9fa31285)

Could you help me?

My configuration:
```yaml
showTree: true
treeExpanded: false
```

### Steps to replicate

Setup a model with `SimpleTree` trait and then enable `showTree` in your `config_list.yaml`

**Comment by goldmont** [comment]
HTTP request seems fine.

Expanding first node:
![image](https://github.com/wintercms/winter/assets/6855692/fce8370d-d86c-48d3-ac5f-e2bda540a6e3)

Expanding second node:
![image](https://github.com/wintercms/winter/assets/6855692/d7f96b12-eaa5-4754-830f-94e3565ac14c)

**Comment by LukeTowers** [comment]
@goldmont @der-On any chance this is related to https://github.com/wintercms/winter/commit/555f13027e7cc0ceedfb7df715d98ad4b053e391?

**Comment by der-On** [comment]
@goldmont I'm sorry I can't confirm/reproduce this. Have you checked that the models table has all required fields?

**Comment by goldmont** [comment]
> @goldmont I'm sorry I can't confirm/reproduce this. Have you checked that the models table has all required fields?

Hi,

it's working now without any change to the codebase.

However, I noticed that the browser remembers whether a node was expanded or not by opening the URL into another tab. So I thought it was a cache issue.
