### ISSUE TITLE
Creating local theme through the backend results in an exception.

### ISSUE THREAD

**Issue by qroft** [wintercms/winter#1162]
### Winter CMS Build

1.2

### PHP Version

Other (please specify below)

### Database engine

SQLite

### Issue description

I can not create a theme through the backend as it results in "Cms\Classes\Theme::getConfig(): Return value must be of type array, null returned"
I also noticed that though the directory and its folders are created, the YAML file is totally empty and the composer file is NOT created.

### Steps to replicate

1. Created a new project via Composer
2. Logged inside through 128.0.0.1/backend
3. Went to Settings -> Front-Theme and created a new blank theme.
4. The error appears, i am not able to get back into the themes and for example delete the just created theme.

### Workaround

Create the Theme via php ARTISAN in the command line seems to work, as version.yaml and theme.yaml are created.

**Comment by LukeTowers** [comment]
Already fixed by https://github.com/wintercms/winter/commit/d940617a35e4e0181aec43d14191347e8d69f6a0, available now on the develop branch or will be available soon in 1.2.7.
