### ISSUE TITLE
Replaced plugin message

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#118]
I installed Winter 1.1.3
Then the winter.user installed the plugin:
```
composer require winter/wn-user-plugin
```

Now on the page `/backend/system/updates` there is a message that you need to remove the rainlab.user plugin.

![2021-04-26_110034](https://user-images.githubusercontent.com/61043464/116053573-82c7f080-a683-11eb-9adf-4da6c88c1097.jpg)

I did not install the rainlab.user plugin.

**Comment by LukeTowers** [comment]
Fixed by #122, will be available in 1.1.4; available now in the develop branch
