### ISSUE TITLE
crop method not called in ImageResizer

### ISSUE THREAD

**Issue by mjauvin** [wintercms/winter#1185]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When using the ImageResizer with mode:crop, the crop() method never gets called.

### Steps to replicate

Twig markup:
```twig
<img src="{{ 'image-path' | theme | resize(200, 100, {mode: 'crop'}) }}">
```

Plugin boot method:
```php
Event::listen('system.resizer.processCrop', function ($resizer, $localTempPath) {
    trace_log("this won't show up");
});
```

**Comment by bennothommo** [comment]
@mjauvin I'm not sure that using `mode: crop` is synonymous with using the `crop` command in the `ImageResizer` class - it appears that `crop` is just a shortcut method. Further, it appears that the `resize` filter is passing everything through the `resize` method anyway, which just filters down to the `Winter\Storm\Database\Attach\Resize` utility class which does the actual resizing/cropping.

My guess is that the `crop` method was being set up to be used for a separate `crop` filter in Twig.

**Comment by LukeTowers** [comment]
@mjauvin could you provide an example of what you were wanting to use the event for?

**Comment by mjauvin** [comment]
@LukeTowers I created a betterCrop() method that can crop from the different sides & corners of an image and I wanted to use the event for this.

**Comment by LukeTowers** [comment]
@mjauvin so right now you're just using the resize event instead?

**Comment by mjauvin** [comment]
> @mjauvin so right now you're just using the resize event instead?

Correct

**Comment by bennothommo** [comment]
Let's close this off for now unless someone is able to confirm that using `{ mode: crop}` doesn't actually crop the image (regardless of it being passed through to the `resize()` method.
