### ISSUE TITLE
A little bug in Media Manager?

### ISSUE THREAD

**Issue by kukrik** [wintercms/winter#1193]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

Hello! I'm new here and installed Winter CMS for the first time. Everything worked perfectly for me. I was also able to log in and edit.

I had some experience with October CMS, I did it as a one-off project for a friend about a few or four years ago.

Just in case, I mention in advance that I have met the minimum requirements set by Winter CMS!

Thanks for the quick feedback!

### Steps to replicate

Today I did a bit of research on Media Manager and tried to upload a few images. The upload worked fine, but then the images were broken. I researched a bit and looked in the directory, then /storage/app/media/images (exists). But there are no processed images in the "resized" folder.

Am I missing or missing something? Or is it really a small bug?

**Comment by kukrik** [comment]
Let me clarify again, actually the version of Winter CMS is v1.2.6. To make the picture clearer!

I would be grateful if someone could answer!

**Comment by LukeTowers** [comment]
@kukrik sounds like your nginx configuration isn't allowing the requests to the /resizer route to make it to the Winter application. 

See "Resizer support when using custom Nginx config" on https://wintercms.com/docs/v1.2/docs/setup/configuration#nginx-configuration

**Comment by kukrik** [comment]
Thanks @LukeTowers for the relatively quick feedback!

I realize now that I didn’t explain myself clearly enough. My answer is no, I understand the Nginx setup. I use Homebrew for development. Since I have multiple projects in development, I created a separate folder for Winter CMS, so it comes up as something like http://localhost/kaar.

In the MediaManager, images are not displaying. I did some debugging in the console and discovered in the Inspector that, for example, there was 
`<img src="/resizer/f0cc292b677343e6722762ec20bd9e2023e25c98/%252Fstorage%252Fapp%252Fresized%252Fbf1%252F4df%252Fb56%252F1_resized_bf14dfb56c5038b570a7c206e1742883b8f4f47c.jpg">`

But in the console, it threw an error:
`<img src="http://localhost/resizer/f0cc292b677343e6722762ec20bd9e2023e25c98/%252Fstorage%252Fapp%252Fresized%252Fbf1%252F4df%252Fb56%252F1_resized_bf14dfb56c5038b570a7c206e1742883b8f4f47c.jpg">`

I ran a few tests and got it working like this:
`<img src="http://localhost/kaar/resizer/f0cc292b677343e6722762ec20bd9e2023e25c98/%252Fstorage%252Fapp%252Fresized%252Fbf1%252F4df%252Fb56%252F1_resized_bf14dfb56c5038b570a7c206e1742883b8f4f47c.jpg">`

I tried setting up Winter CMS as the only project on the development server and temporarily moved the other projects elsewhere (of course, I moved them back afterward), but there was no difference, whether it was the root folder or a subfolder, etc.

After some extended investigation, I came up with a result, and I think you guys should include it. But as for how and in what form to do so, I can’t say for sure—you’ll know better how to handle it.

I found the issue in this file: /modules/backend/widgets/mediamanager/partials/_thumbnail-image.php.

I changed the following line:

`<img src="<?= $imageUrl ?>"/>`
to:
`<img src="<?= Config::get('app.url') . $imageUrl ?>"/>`

After that, it started working as expected.

Since I'm not very familiar with the core of Winter CMS (I only have some basic knowledge), I'm not sure if this is the best way to handle it. Perhaps this logic should be added to /modules/backend/widgets/mediamanager/Lists.php somewhere around lines 1311-1316, where it might be more appropriate.

In my opinion, the <img> tag should always contain the full URL to ensure it works correctly for everyone, as it might not function properly without it in some environments.

I will be listening to you soon!

**Comment by LukeTowers** [comment]
@kukrik see https://github.com/wintercms/winter/blob/develop/config/cms.php#L307-L315. I'd welcome a PR to add a note about using Winter in a subfolder to our documentation: https://wintercms.com/docs/v1.2/docs/setup/configuration

**Comment by kukrik** [comment]
Thank you for the quick response!

I just remembered that before this, I had spent quite some time testing and also set the configuration in the place you mentioned:

```
'storage' => [
    'uploads' => [
        'disk' => 'local',
        'folder' => 'uploads',
        'path' => '/storage/app/uploads',
        'temporaryUrlTTL' => 3600,
    ],
    'media' => [
        'disk' => 'local',
        'folder' => 'media',
        'path' => '/kaar/storage/app/media',
    ],
    'resized' => [
        'disk' => 'local',
        'folder' => 'resized',
        'path' => '/kaar/storage/app/resized',
    ]
],

```
In my case, the 'resized' options didn't seem to work for me. Just mentioning this for the awareness of others!

**Comment by kukrik** [comment]
Hello again!

I need to quickly report that it's very interesting to see how Winter CMS behaves differently in my Homebrew development environment compared to when I moved it to a production environment. In production, I had to remove the `Config::get('app.url')` adjustment. Winter CMS works as expected in its original form in the production environment.

I have other projects developed and being developed in the Homebrew environment, and they have been successfully deployed to production in the same condition without issues.

Now, I’m unsure whether this discrepancy should be considered or not.

Therefore, it’s up to you to decide whether to take this difference into account or not!

**Comment by kukrik** [comment]
Additionally, I want to point out that when I left Config::get('app.url') in the production environment, I noticed that it adds a trailing slash to the URL.

Here’s a specific example:

`<img src="https://www.example.com/kaar//resizer/f0cc292b677343e6722762ec20bd9e2023e25c98/%252Fstorage%252Fapp%252Fresized%252Fbf1%252F4df%252Fb56%252F1_resized_bf14dfb56c5038b570a7c206e1742883b8f4f47c.jpg">`

After removing it, it works as expected:

`<img src="/resizer/f0cc292b677343e6722762ec20bd9e2023e25c98/%252Fstorage%252Fapp%252Fresized%252Fbf1%252F4df%252Fb56%252F1_resized_bf14dfb56c5038b570a7c206e1742883b8f4f47c.jpg">`

Just some additional information for your reference!

**Comment by LukeTowers** [comment]
@kukrik you shouldn't need the modification you made, all the URLs are generated according to your configs.

**Comment by kukrik** [comment]
Clear! The differences between Homebrew and a production environment remain a bit of a mystery to me.

It's okay and I'll close the topic!
