### ISSUE TITLE
Log is Undefined in storm/src/Support/helpers.php

### ISSUE THREAD

**Issue by SpherAx** [wintercms/winter#1196]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

PostgreSQL

### Plugins installed

Winter.Demo, Winter.User, Winter.Blog, Winter.Forum, Winter.Notify, Flynsarmy.SocialLogin

### Issue description

The `Log::$level($message);` statement on approximately line 150 throws an error because the file does not use Illuminate\Support\Facades\Log.

### Steps to replicate

Attempt to use the Auth facade in an event listener.

### Workaround

Add `use Illuminate\Support\Facades\Log` to the top of storm/src/Support/helpers.php

**Comment by damsfx** [comment]
> The Log::$level($message); statement on approximately line 150 throws an error
Maybe you can tell us in which file and the exact line where this code is?

**Comment by LukeTowers** [comment]
Why is it throwing an exception? It should be using the global alias: https://github.com/wintercms/storm/blob/develop/src/Support/helpers.php#L153 & https://github.com/wintercms/storm/blob/bc8f449672017915b2a64dbaf9f838d6bbe40940/src/Foundation/Application.php#L471

Are you trying to load that file directly outside of the context of a booted application?

**Comment by bennothommo** [comment]
No harm in linking to the facades, but as @LukeTowers said, if you're loading this outside of the context of a booted application, you're likely going to get a `Facade root not found` error or something similar.
