### ISSUE TITLE
 Unhandled error in storm/src/Html/FormBuilder.php

### ISSUE THREAD

**Issue by SpherAx** [wintercms/winter#1197]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

PostgreSQL

### Plugins installed

Winter.Demo, Winter.User, Winter.Blog, Winter.Forum, Winter.Notify, Flynsarmy.SocialLogin

### Issue description

The `if (!strlen($name))` condition on approximately line 980 throws an unhandled exception if $name is null because passing a null parameter to strlen() is deprecated in PHP 8.1.

### Steps to replicate

Unknown what exactly caused this to occur but easy to fix.

### Workaround

Simply change the condition to `if($name)`.

**Comment by LukeTowers** [comment]
@SpherAx you don't have to submit issues for simple fixes, just submit a PR and provide your justification there instead.

**Comment by LukeTowers** [comment]
Better solution would be to add type hints to that method and then provide an empty string as a default value to array_get where the variable is populated before being passed to that method: https://github.com/wintercms/storm/blob/develop/src/Html/FormBuilder.php#L116
