### ISSUE TITLE
Cannot install on laravel 11

### ISSUE THREAD

**Issue by kriit24** [wintercms/winter#1205]
### Winter CMS Build

1.2

### PHP Version

Other (please specify below)

### Database engine

MySQL/MariaDB

### Issue description

Cannot install wintercms/winter

error:

` Problem 1
    - wintercms/winter[v1.0.319, ..., v1.0.420] require october/rain dev-develop -> found october/rain[dev-develop, 3.x-dev (alias of dev-develop)] but it does not match your minimum-stability.
    - wintercms/winter[v1.0.348, ..., v1.0.419] require laravel/framework 5.1.* -> found laravel/framework[v5.1.0, ..., v5.1.46] but it conflicts with your root composer.json require (^11.9).
    - wintercms/winter[v1.0.421, ..., v1.0.461] require laravel/framework 5.5.* -> found laravel/framework[v5.5.0, ..., v5.5.50] but it conflicts with your root composer.json require (^11.9).
    - wintercms/winter[v1.0.462, ..., v1.0.464] require laravel/framework ^5.5.40 -> found laravel/framework[v5.5.40, ..., v5.8.38] but it conflicts with your root composer.json require (^11.9).
    - wintercms/winter[v1.0.465, ..., v1.0.475] require laravel/framework ~5.5.40 -> found laravel/framework[v5.5.40, ..., v5.5.50] but it conflicts with your root composer.json require (^11.9).
    - wintercms/winter[v1.1.0, ..., v1.1.10] require laravel/framework ~6.0 -> found laravel/framework[v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^11.9).
    - wintercms/winter[v1.2.0, ..., v1.2.6] require laravel/framework ^9.1 -> found laravel/framework[v9.1.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9).
    - Root composer.json requires wintercms/winter * -> satisfiable by wintercms/winter[v1.0.319, ..., v1.2.6].
`

### Steps to replicate

composer require --ignore-platform-reqs wintercms/winter

**Comment by mjauvin** [comment]
Laravel 11 support has not been merged yet, but you can install it like this in the meantime:

```bash
composer create-project wintercms/winter winter-laravel11 dev-wip-laravel-11
```

**Comment by kriit24** [comment]
how can i composer require, if i already  have project ?

On 13.09.2024 14:11, Marc Jauvin wrote:
> composer create-project wintercms/winter winter-laravel11 
> dev-wip-laravel-11

-- 
Lugupidamisega,
Kuno Vaik
IT Project Partner OÜ
+372 58 4444 84
www.projectpartner.ee

**Comment by mjauvin** [comment]
Use "dev-wip-laravel-11" for all winter packages in your `composer.json`:
```json
        "winter/storm": "dev-wip-laravel-11",
        "winter/wn-system-module": "dev-wip-laravel-11",
        "winter/wn-backend-module": "dev-wip-laravel-11",
        "winter/wn-cms-module": "dev-wip-laravel-11",
        "laravel/framework": "^11.0",
```
Then run `composer update`
