### ISSUE TITLE
BC in FormWidgets behavior

### ISSUE THREAD

**Issue by mjauvin** [wintercms/winter#1219]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap

### Issue description

The following commits break some formwidgets (e.g. `Winter\Sitemap\FormWidgets\SitemapItem`)

- f8459b4c76ab9bb22c95c336f665818afb6837c0
- 27776b6c9a153267f417cb46e1f4ef327ec4b512

### Steps to replicate

- An an item in the Sitemap Definition and save the form.
- Reload the form
- Item has not been saved

**Comment by mjauvin** [comment]
For the Winter.Sitemap plugin, the problem happens because the post data has a different structure than what the Form widget's `getSaveData()` method expects.

**Comment by LukeTowers** [comment]
The addition of the following code in the getSaveData() method does technically represent a BC-break to the functionality as it existed:

```php
// Exclude fields that didn't provide any value
$fieldValue = $this->dataArrayGet($result, $parts, FormField::NO_SAVE_DATA);
if ($fieldValue === FormField::NO_SAVE_DATA) {
    continue;
}
```

However, after discussion with @bennothommo we've landed on the fact that any FormWidgets relying on the previous behaviour were incorrect and should not have been doing so. A FormWidget should by its very nature always have a value that can be referenced within the context of the form as it essentially represents a more complex field within that form. The form widget in question that broke (https://github.com/wintercms/wn-sitemap-plugin/pull/18) was making use of a hacky approach to managing the data it was responsible for and thus should be changed.

FormWidgets are free to have a somewhat loose connection between the data that is stored and retrieved and how that data is interacted with / expanded / contracted within the UX of the FormWidget itself, but fundamentally it should always be storing and retrieving a value from which it can function and play nice with the rest of the form system.

Recommend that the FormWidget in question adapt to using a data locker pattern for storing / retrieving the data as the way forward.
