### ISSUE TITLE
TagList not saving an empty value

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#1223]
It appears that a `TagList` widget in `relation` mode is not saving an empty value, because it no longer sends a POST value when empty.

### Replication steps

In the Test plugin:

- Go to **Users**, edit either user.
- Click **Tag List Field** in the top alternative views box.
- Empty the **Roles** field, then try and save.

It does not fail validation, so the form saves, as the last value in the tag list is kept on refresh even though all tags are removed.

**Comment by mjauvin** [comment]
@bennothommo are you suggesting it's possible to send an empty value in the Post data?

**Comment by bennothommo** [comment]
@mjauvin most certainly.

**Comment by mjauvin** [comment]
> [@mjauvin](https://github.com/mjauvin) most certainly.

How do you do that ? (I mean in respect to the TagList formwidget)

**Comment by AIC-BV** [comment]
> `relation` mode

It doesn't work in `update` mode either
But its fixed with your PR. Thanks!
