### ISSUE TITLE
Upgrade twig/twig to fix "Possible sandbox bypass" CVE

### ISSUE THREAD

**Issue by nmiyazaki-chapleau** [wintercms/winter#1246]
Twig/twig had a CVE reported on 2024-09-09 about a possible sandbox bypass. Although the circumstances for this CVE to be applicable are specific, we should update twig/twig to mitigate this.
Link: [https://symfony.com/blog/twig-security-release-possible-sandbox-bypass](https://symfony.com/blog/twig-security-release-possible-sandbox-bypass)
Current twig/twig version constraint: <3.9
Fix twig/twig version: 1.44.8, 2.16.1, and 3.14.0.

**Comment by LukeTowers** [comment]
@mjauvin are there any remaining incompatibilities with 3.14 and Winter?

**Comment by mjauvin** [comment]
@LukeTowers no, we're already using latest version of twig 3.X

The incompatibllities are with 4.x

**Comment by nmiyazaki-chapleau** [comment]
You are correct; I just checked, and the 1.2 branch of winter/storm requires twig <3.9, but the develop branch does not. Are there any news regarding a release for this? Thanks!

**Comment by LukeTowers** [comment]
@nmiyazaki-chapleau yes, we'll be making a new release soon
