### ISSUE TITLE
Installer not accessible

### ISSUE THREAD

**Issue by w3labz** [wintercms/winter#127]
Just wanted to test drive the manual installer, but URL https://github.com/wintercms/web-installer/archive/refs/heads/main.zip is showing an error -Not Found   

from page https://wintercms.com/docs/setup/installation#wizard-installation

**Comment by josieit** [comment]
Hi, if I understood correctly the web installer will be available soon (~ next week).

You will be able to access it from https://wintercms.com/download

**Comment by w3labz** [comment]
Ideally bug shall be closed once its fixed. 
But its your space you can do anything. Or you shall remove the link from this page https://wintercms.com/docs/setup/installation#wizard-installation


1. Prepare a directory on your server that is empty. It can be a sub-directory, domain root or a sub-domain.
2. **[Download the installer archive file.*](https://wintercms.com/download)*
3. Unpack the installer archive to the prepared directory.
4. Grant writing permissions on the installation directory and all its subdirectories and files.
5. Navigate to the install.php script in your web browser.
6. Follow the installation instructions.

**Comment by LukeTowers** [comment]
I prefer we leave this issue open until it's resolved @mjauvin, lots of people are asking

**Comment by Sameto** [comment]
Thanks for prioritising this. Shared hosting can be a pain without it.

**Comment by TrenchTown** [comment]
When to expect the installer approximately ?

**Comment by bennothommo** [comment]
@TrenchTown I don't want to commit to a date yet, but we have made substantial progress on the inner workings of the Installer and are nearly close to completion. Just a little longer :)

**Comment by arvislacis** [comment]
@bennothommo As Web installer has been released then this may be closed.

**Comment by bennothommo** [comment]
Thanks for the reminder @arvislacis.

If anyone comes across this issue when looking for the Web installer, please see this post for more info: https://wintercms.com/blog/post/web-installer-now-available.
