### ISSUE TITLE
Stripe conifguration with data attribute is not compiled

### ISSUE THREAD

**Issue by webbati** [wintercms/winter#1274]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

The data attribute "data-request-stripe" not working cause updated AttributeRequest.js is not compiled in snowboard.data-attr.js

ref. PR https://github.com/wintercms/winter/pull/1201

### Steps to replicate

use `data-request-stripe="false"`

### Workaround

Recompiling assets with `php artisan mix:compile -f` in the root directory of Winter installation

**Comment by bennothommo** [comment]
I've recompiled the assets as of https://github.com/wintercms/winter/commit/d2d55ef3948259494773d8ad18f22b637f993463. It will be released with the next point release.

In the mean time, if you need access to that attribute, you will need to compile the assets in your project with `php artisan mix:compile --production`, or alternatively, copy our [snowboard.data-attr.js](https://github.com/wintercms/winter/blob/develop/modules/system/assets/js/snowboard/build/snowboard.data-attr.js) build and place it in the `modules/system/assets/js/snowboard/build` folder of your project, overwriting the previous version.
