### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by GinoPane** [wintercms/winter#132]
Hi guys!

Is everything ok with the website?

![image](https://user-images.githubusercontent.com/3897579/116620207-319d5280-a94a-11eb-80f3-48cdacb41745.png)

Also the discord link seems to be broken:

![image](https://user-images.githubusercontent.com/3897579/116620290-4d085d80-a94a-11eb-9ff6-2705e3de3302.png)

**Comment by LukeTowers** [comment]
@GinoPane thanks for the report, pushed a bug fix earlier today but it looks like the cache clear never ran so I ran it manually and it's fine now. Discord link seems fine to me, what link are you using? https://discord.com/invite/D5MFSPH6Ux is the correct one.

**Comment by GinoPane** [comment]
I used the one from the website and also from the github issue template.

**Comment by GinoPane** [comment]
@LukeTowers yours does not work for me either:

![image](https://user-images.githubusercontent.com/3897579/116621036-46c6b100-a94b-11eb-8680-c1808df641b1.png)

**Comment by LukeTowers** [comment]
What is your user name?

**Comment by GinoPane** [comment]
@LukeTowers ah, sorry, nevermind. The issue was with Discord itself. It invalidated my login for whatever reason and forced me to change my password this way. Once it's done, I was able to accept the invite.
