### ISSUE TITLE
Problems running latest code with PHP 7.0 / Laravel 5.5

### ISSUE THREAD

**Issue by amjadniazi48** [wintercms/winter#160]
After migrating my project to wintercms from octobercms I am facing these problems with composer update command
I am using xampp  with PHP 7.4

 ` Problem 1
    - Root composer.json requires winter/storm dev-develop as 1.1.999 -> satisfiable by winter/storm[dev-develop].
    - winter/storm dev-develop requires php >=7.2.9 -> your php version (7.0; overridden via config.platform, actual: 7.4.13) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires winter/wn-system-module dev-develop as 1.1.999 -> satisfiable by winter/wn-system-module[dev-develop].
    - winter/wn-system-module dev-develop requires php >=7.2 -> your php version (7.0; overridden via config.platform, actual: 7.4.13) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires winter/wn-backend-module dev-develop as 1.1.999 -> satisfiable by winter/wn-backend-module[dev-develop].
    - winter/wn-backend-module dev-develop requires php >=7.2 -> your php version (7.0; overridden via config.platform, actual: 7.4.13) does not satisfy that requirement.
  Problem 4
    - Root composer.json requires winter/wn-cms-module dev-develop as 1.1.999 -> satisfiable by winter/wn-cms-module[dev-develop].
    - winter/wn-cms-module dev-develop requires php >=7.2 -> your php version (7.0; overridden via config.platform, actual: 7.4.13) does not satisfy that requirement.
  Problem 5
    - Root composer.json requires wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].
    - wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your php version (7.0; overridden via config.platform, actual: 7.4.13) does not satisfy that requirement.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific
versions.`

**Comment by rubenvanerk** [comment]
Seems like you set [`config.platform`](https://getcomposer.org/doc/06-config.md#platform) in your composer.json to 7.0. That setting overrides the version you're using (7.4).
Either change this value to 7.4 or remove it. Then it should work.

**Comment by amjadniazi48** [comment]
Its not working i think the problem is with laravel version because I m using laravel version 5.5, now i m getting these problem after changing the value to 7.4

Problem 1
    - Root composer.json requires winter/storm dev-develop as 1.1.999 -> satisfiable by winter/storm[dev-develop].
    - winter/storm dev-develop requires laravel/framework ~6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev] but it conflicts
with your root composer.json require (5.5.*).
  Problem 2
    - Root composer.json requires winter/wn-system-module dev-develop as 1.1.999 -> satisfiable by winter/wn-system-module[dev-develop].
    - winter/wn-system-module dev-develop requires laravel/framework ~6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (5.5.*).
  Problem 3
    - Root composer.json requires winter/wn-backend-module dev-develop as 1.1.999 -> satisfiable by winter/wn-backend-module[dev-develop].
    - winter/wn-backend-module dev-develop requires laravel/framework ~6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (5.5.*).
  Problem 4
    - Root composer.json requires winter/wn-cms-module dev-develop as 1.1.999 -> satisfiable by winter/wn-cms-module[dev-develop].
    - winter/wn-cms-module dev-develop requires laravel/framework ~6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (5.5.*).

**Comment by rubenvanerk** [comment]
That seems to be the issue. You should upgrade Laravel to 6. Check out the upgrade notes on how to do that: https://github.com/wintercms/meta/blob/master/l6-upgrade-notes.md
