### ISSUE TITLE
Plugin migrations issue via composer

### ISSUE THREAD

**Issue by GinoPane** [wintercms/winter#170]
There's a strange issue when installing a plugin via composer.

Here's the reference: https://github.com/GinoPane/wn-blogtaxonomy-plugin/issues/2

When the plugin is installed via composer, we see that migrations are running (at least they are shown in the console), but when you try to use the plugin after that, you see that some tables were not created.

But, if you run `php artisan plugin:refresh ginopane.blogtaxonomy` all migrations are run and all tables are created.

Did you guys see anything similar? Should some specific options be set in composer.json maybe? The plugin relies on a "Winter Blog".

**Comment by josephcrowell** [comment]
Did you use the replaces property on the plugin? If so, it doesn't run version migrations for earlier versions on the plugin that is replaced. Hope you understand what I mean.

**Comment by bennothommo** [comment]
@GinoPane is this on a fresh install, or on a project converted to Winter CMS?

**Comment by GinoPane** [comment]
@josephcrowell 
Nope I didn't. Basically it is a fresh install.

@bennothommo 
It was for a fresh project. You can install a fresh dev copy of Winter CMS, install the plugin via composer and see the issue. 
And "artisan refresh" will solve it.

**Comment by bennothommo** [comment]
@GinoPane thanks. Giving it a try now.

**Comment by bennothommo** [comment]
@GinoPane can't seem to replicate it, unfortunately. I was able to access the Blog area just fine after installing the Taxonomy plugin through Composer:

![image](https://user-images.githubusercontent.com/15900351/118094691-a324d880-b401-11eb-8c5a-ad50c2a56244.png)

Might need some more information on the steps taken that ended up exhibiting the issue.

EDIT: I tested with Winter CMS 1.1.3 - did you try it on `dev-develop`?

**Comment by GinoPane** [comment]
Ah, I probably understood the issue...

Split of two projects added some uncertainties. 

So, when installing plugins via composer, migrations are **not** actually installed in Winter CMS. But, migrations are running when you log in into the backend.

So to reproduce this you need to be logged in already. When you are logged in and you install a plugin in background through composer, you'll get an error:

![image](https://user-images.githubusercontent.com/3897579/118107366-546a4500-b3e7-11eb-97ec-7892ee866837.png)

---

And to be honest I'm not sure now if it's an issue or not. Probably not, as long as it is an expected behavior for Winter CMS that migrations are not running during plugin installation via `composer`.

**Comment by GinoPane** [comment]
Maybe it is worth adding an post-install action for a plugin though...

**Comment by mjauvin** [comment]
@GinoPane you must run `artisan winter:up` after installing a plugin via composer.

**Comment by bennothommo** [comment]
@GinoPane we don't run migrations automatically with Composer, as there's no guarantee that the database is available at that time (mostly in the case of new projects when the configuration hasn't been updated yet). It is up to the developer to run the migrations through `winter:up` whenever installing a plugin through Composer, as @mjauvin said.

I'll close this for now, but let us know if we need to follow up with anything else and I'll re-open.
