### ISSUE TITLE
resize - Cached resized image provided even if it the original changed

### ISSUE THREAD

**Issue by helmutkaufmann** [wintercms/winter#177]
- Winter CMS Build: 1.1.3
- PHP Version: 8 (and 7.4)
- Database Engine: sqlite
- Plugins Installed: 

### Description:

When an image that has been resized using Winter's built-in resize Twig function, is replaced, the resize does not identify that and provides the resized version of the ORIGINAL image instead of the NEW image - probably as the modification date of the replaced image is not checked against the creation date of the resized image.

Note that https://github.com/toughdeveloper/oc-imageresizer-plugin provides a resize that actually checks for image file modification time and re-generates the images as needed. Perhaps this would be a solution.

### Steps To Reproduce:
1) Place an image in the media directory and resize it, "image.jpg" | media | resize(200, 200)
2) Replace image.jpg with another image
3) Re-run  "image.jpg" | media | resize(200, 200) --> the old image is served.

**Comment by LukeTowers** [comment]
@helmutkaufmann can you give https://github.com/wintercms/winter/pull/178 a try and let me know your thoughts?

**Comment by helmutkaufmann** [comment]
Elegant solution, I have to admit. The PR works as I would have expected it. The only drawback I see is that this solution will result in a number of "orphaned resized" images but we will have those anyway when we remove images that have been resized.

**Comment by LukeTowers** [comment]
@helmutkaufmann do you have any ideas for a console command that could automatically identify orphaned resized images and delete them?

**Comment by LukeTowers** [comment]
Only things that comes to my mind is just a command that purges all resized images to force a global reset.

**Comment by helmutkaufmann** [comment]
> @helmutkaufmann do you have any ideas for a console command that could automatically identify orphaned resized images and delete them?

One could actually write a command that goes through the resized directory, extract the original file names and check if the originals still exist. An remove the resized ones if not.

**Comment by LukeTowers** [comment]
I'd be willing to see an attempt be made for that, but I don't think the resized image name is reversable tbh, at least part of it consists of a one way hash of the configuration.

**Comment by helmutkaufmann** [comment]
Looking at ImageResize.php, the configuration should be available in the cache. However, if I read the Laravel documentation correctly, there is no way to iterate over all cached items (or all items with a select prefix). In that case we might indeed be out of luck.

**Comment by helmutkaufmann** [comment]
The information of the source images would at least be in the cache. To make use of this, one would have to iterate over all the cached items with the CACHE_PREFIX prefix and check the. I don't think one can iterate over all cache items and even if we could, the information would be lost upon cache:clear.

**Comment by helmutkaufmann** [comment]
Looking at https://github.com/wintercms/winter/pull/178, a way of achieving this would be to include the identifier of the Cache item (which is, eg "system.resizer.48005fd9c28f24997e3fffb92c1a88f3ddccd0be") in the filename of the resize image. With hat it would be possible to get back to the originals. And it would also allow to implement a command that not only removes orphaned images but also their orphaned Cache items. Assuming that the cache has not been cleared.

**Comment by LukeTowers** [comment]
Image resizer config data does not stay in the cache after the image has been resized, see https://github.com/wintercms/winter/blob/develop/modules/system/classes/ImageResizer.php#L733-L734

**Comment by helmutkaufmann** [comment]
Still think we should implement this change.

**Comment by LukeTowers** [comment]
@helmutkaufmann it's still planned, just need a command to clear out the resized images directory.

**Comment by helmutkaufmann** [comment]
> @helmutkaufmann it's still planned, just need a command to clear out the resized images directory.

You mean an artisan command clearing out ALL resized images? That I could write.

**Comment by LukeTowers** [comment]
@helmutkaufmann yes, probably under the winter:util command, something like `winter:util purge resized`

**Comment by LukeTowers** [comment]
Fixed in https://github.com/wintercms/winter/commit/78a720146145fcf234fbbb412c049e4f4440b094
