### ISSUE TITLE
Add support for MorphPivot

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#18]
Refs: octobercms/library#534 & octobercms/docs#496

**Comment by LukeTowers** [comment]
@bennothommo is this related to your relationship refactor PR to storm?

**Comment by bennothommo** [comment]
@LukeTowers nope, I don't think we have MorphPivot support yet.

**Comment by bennothommo** [comment]
Morph Pivot support has been added: https://github.com/wintercms/storm/pull/64

**Comment by mjauvin** [comment]
Resolved by https://github.com/wintercms/storm/pull/64

**Comment by mjauvin** [comment]
@bennothommo I closed this. just a note in case you needed to do something before closing it.

**Comment by bennothommo** [comment]
All good @mjauvin, nothing else needed to be done here :)
