### ISSUE TITLE
Event not listened to: system.resizer.getAvailableSources

### ISSUE THREAD

**Issue by helmutkaufmann** [wintercms/winter#194]
- Winter CMS Build: dev-develop 0a729ee 
- PHP Version: 7.4 or 8, both don't work
- Database Engine: sqlite
- Plugins Installed: none / one, see below

### Description:
Adding the following event handler to boot() of a plugin causes the plugin to not load anymore
```
 Event::listen('system.resizer.getAvailableSources', function ((array) &$sources)) {
        
                  $sources['portfolio'] = [
                       'disk' => 'portfolio',
                       'folder' => '/',
                       'path' => '/storage/portfolio',
                  ];
                  
              });
```

See also related Discord trail with @mjauvin: https://discord.com/channels/816852513684193281/821159568763125800/847911632940040232

### Steps To Reproduce:

Create new Winter instance
Create new plugin with artisan create:plugin
Add the above event listener to boot() of the plugin
artisan winter:up does not list the plugin
remove the listener --> artisan winter:up just works fine

**Comment by LukeTowers** [comment]
Did you set your plugin to elevated access? The image resizer is a protected route, along with the asset combiner.

**Comment by helmutkaufmann** [comment]
Found it - after a day: 
```
 Event::listen('system.resizer.getAvailableSources', function ((array) &$sources)) 
```
The type cast (array) causes this. Replacing it by 
```
Event::listen('system.resizer.getAvailableSources', function (&$sources) {
		
		EventLog::add("Listening to system.resizer.getAvailableSources");
		
                  $sources['portfolio'] = [
                       'disk' => 'portfolio',
                       'folder' => '/',
                       'path' => '/storage/portfolio',
                  ];

              });                  
 ```
makes it work just fine. Perhaps worth changing the documentation in the source code at one time.

**Comment by LukeTowers** [comment]
What's the specific error that you're getting? The type casts in the docs are usually more for your own reference than a recommended inclusion, but I'm curious to know why it failed.
