### ISSUE TITLE
Improve UX for filtered list views

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#199]
This has probably been reported before, but it would be nice if we could make list views that have been filtered (whether through filter scopes or searches) more obvious to end users, something like a "You are viewing a filtered set of results. **Clear filters**" and or in the pagination "1 of 5 filtered results, 4000 total".

**Comment by RomainMazB** [comment]
Wouldn't it be nice that additionally to the "clear all filters", a list of selected filters is displayed similarly to the `TagList` widget allowing the user to unselect just one or another:
```
You are viewing a filtered set of results [Clear all filters]: [Created at: From 1/1/2021 to 2/1/2021 {x}] [Status: Published {x}] [User: Romain {x}]
```
For sure this adds extra work but I feel like just adding the clear all filters button is just like doing the half of the work. 

EDIT: That said, we can already unselect filters individually through the existing UI dropdowns. This would just add a more direct and visual way to do it.
