### ISSUE TITLE
method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

### ISSUE THREAD

**Issue by tospe** [wintercms/winter#207]
- Winter CMS Build: ### 1.1.3
- PHP Version: 8.0.7
- Database Engine: mysql
- Plugins Installed: Arcane.Seo (https://github.com/quangtrongonline/Arcane-SEO), Winter.Blog

### Description:

When visiting a blogpost page with Seo component this error appears. 
![Screenshot 2021-06-17 at 09 58 30](https://user-images.githubusercontent.com/49151314/122365620-bb34ce00-cf52-11eb-8146-3861f6d29ce4.png)
After digging about this problem I found that ["method_exists() is too strict in PHP 8"](https://bugs.php.net/bug.php?id=79623). This is happening in many places [wordpress](https://wordpress.org/support/topic/php8-php-fatal-error-uncaught-typeerror-method_exists/), [drupal](https://www.drupal.org/project/drupal/issues/3173958), etc

### Steps To Reproduce:
- install wintercms (with php 8), with winter.blog and Arcane.Seo
- add the Seo component to the post page   

### Possible solution 
As proposed in Drupal [patch](https://www.drupal.org/files/issues/2020-09-30/3173958-2.patch) we should bail earlier on null. I managed to pass the error by changing  public function __call($method, $parameters) in modules/cms/classes/ComponentBase by bailing earlier on null:

```
    public function __call($method, $parameters)
    {
        try {
            return parent::__call($method, $parameters);
        }
            catch (BadMethodCallException $ex) {
        }
        
        // proposed change
        if($this->controller == NULL){
            return NULL;
        }
        //end 
                
        if (method_exists($this->controller, $method)) {
            return call_user_func_array([$this->controller, $method], $parameters);
        }

        throw new BadMethodCallException(Lang::get('cms::lang.component.method_not_found', [
            'name' => get_class($this),
            'method' => $method
        ]));
    } ```

**Comment by bennothommo** [comment]
@tospe We will look into this, however, in PHP 7.2-7.4, `null` would pass that condition and would go to the `BadMethodCallException` below, so it seems that the component itself might have an issue.

**Comment by LukeTowers** [comment]
Code change would probably be `if ($this->controller && method_exists($this->controller, $method)) {`

**Comment by tospe** [comment]
> @tospe We will look into this, however, in PHP 7.2-7.4, `null` would pass that condition and would go to the `BadMethodCallException` below, so it seems that the component itself might have an issue.

Thank you for the fast response. 

As said in in [method_exists() is too strict in PHP 8](https://bugs.php.net/bug.php?id=79623) method_exists(), in php 8, only accepts an object|string as 1st argument.  

I checked the component the error happens in 
`if (! $this->page['viewBag']) $this->page['viewBag'] = "new ViewBag";`

**Comment by bennothommo** [comment]
@tospe 

> As said in in method_exists() is too strict in PHP 8 method_exists(), in php 8, only accepts an object|string as 1st argument.

I understand, but what I mean is that the fact that `$this->controller` is `null` at all would indicate an issue with the component.

**Comment by tospe** [comment]
@bennothommo 
> I understand, but what I mean is that the fact that `$this->controller` is `null` at all would indicate an issue with the component.

You are right. I found the issue, viewBag wasn't being called correctly.

Thank you for you help.

**Comment by bennothommo** [comment]
@tospe I'll leave this open, as we'll need to audit our `method_exists` usage and see if this new behaviour by PHP 8 will catch us out anywhere.

**Comment by LukeTowers** [comment]
@bennothommo if you could take a look at this, looks like this issue gets the most amount of traffic according to the insights tab.
