### ISSUE TITLE
fallback_locale will be ignored

### ISSUE THREAD

**Issue by Kuse-GmbH** [wintercms/winter#220]
- Winter CMS Build: 1.1.3
- PHP Version: 7.3, 7.4. 8.0
- Database Engine: mariaDB 10.4.20
- Plugins Installed: -

### Description:
'fallback_locale' => 'en' will  be ignored in backend mainmenu

I use 'locale' => 'de' in my installation and a plugin gromit.sentmails (there is only one plugin without german translation installed) and in mainmenu there is the translation string:

![Bildschirmfoto_2021-06-30_08-15-34](https://user-images.githubusercontent.com/59687031/123916323-cee42980-d981-11eb-8735-133b6dc3f092.png)

at the top there is a screenshot from winterCMS (booth testet, web installer and composer install), at the bottom an nearly identical oc-install (latest v1)

### Steps To Reproduce:
in app.php:
'locale' => 'de',
'fallback_locale' => 'en',

Install gromit.sentmails

**Comment by mjauvin** [comment]
I can't reproduce this, fallback_locale works fine for me.

**Comment by xitara** [comment]
ok. I will test it on a clean new installation with only this plugin tomorrow and I'll give feedback
thanks

ops. I posted with a different account before. sorry for this.

**Comment by mjauvin** [comment]
Just to clarify, I tried to reproduce with 'locale' => 'fr' and 'fallback_locale => 'en' with a plugin of mine with missing FR strings localizations and the EN version was used (as a fallback).

**Comment by mjauvin** [comment]
Just tried with `gromit.sentmails` and was able to reproduce... I'll report what I find in a few minutes.

**Comment by mjauvin** [comment]
Ok, I found the problem: the plugin is using RainLab.Translate instead of Laravel for its localization...
i.e.
```
    public function registerNavigation(): array
    {   
        return [
            'sentmails' => [
                'label'       => __('gromit.sentmails::lang.menu_label'),
                'url'         => Backend::url('gromit/sentmails/mails'),
                'icon'        => 'icon-envelope-open',
                'permissions' => ['gromit.sentmails.*'],
                'order'       => 500,
            ],
        ];
    }
```

**Comment by mjauvin** [comment]
Note: the plugin should be using this instead:
```
    public function registerNavigation(): array
    {   
        return [
            'sentmails' => [
                'label'       => 'gromit.sentmails::lang.menu_label',
                'url'         => Backend::url('gromit/sentmails/mails'),
                'icon'        => 'icon-envelope-open',
                'permissions' => ['gromit.sentmails.*'],
                'order'       => 500,
            ],
        ];
    }
```

ALL INSTANCES should be replaced in Plugin.php for this to work (everywhere `__()` is used)

**Comment by xitara** [comment]
I want to migrate this plugin with some new features to winterCMS. Then I replace the translations, too

**Comment by mjauvin** [comment]
Is it one of your plugins?

**Comment by mjauvin** [comment]
I submitted a PR to address the issues:

https://github.com/gromitsoft/oc-sentmails-plugin/pull/2
