### ISSUE TITLE
Add support for trusted proxies

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#232]
Laravel 6 has support for trusted proxies (https://laravel.com/docs/6.x/requests#configuring-trusted-proxies) which allows certain setups (such as AWS Elastic Load Balancing, Heroku, Gitpod) where TLS/SSL communications are terminated at the entrypoint to still use HTTPS links even though the actual PHP is not output in a TLS/SSL request.

We currently do not have a similar capacity in Winter CMS, and should probably implement it in similar fashion to the trusted hosts functionality. While it is certainly possible to implement this through a plugin, it might be better being a first-class feature in order for Winter CMS to just "work" in more complex environments.

For example, at the moment, I am unable to access the administration panel of a fresh Winter CMS install in a Gitpod instance, even after setting all possible configuration options for the app URL (`app.url`, `APP_URL`, etc.), because the Symfony `Request` class interprets my request as a non-secure request and converts the protocol of all my redirects, links and assets to `http`. Gitpod, however, communicates through a `https` URL, therefore, at the very least, I have an unstyled login screen - at worse, a redirect loop.

When adding a custom middleware through a plugin to use trusted proxies, which are then populated in the request in a similar fashion to the Laravel docs link above, it works.

Laravel uses the `fideloper/proxy` library to provide this functionality - we can either do the same, or roll our own.

**Comment by matteotrubini** [comment]
This should be also applicable to Cloudflare's flexible SSL setup, right?

**Comment by bennothommo** [comment]
@matteotrubini yep, should likely be able to resolve that too.

**Comment by LukeTowers** [comment]
Sounds good to me

**Comment by LukeTowers** [comment]
@bennothommo can you do up a PR for the config file as well?

**Comment by bennothommo** [comment]
@LukeTowers done :)
