### ISSUE TITLE
PHPUnit tests failing

### ISSUE THREAD

**Issue by avanns** [wintercms/winter#236]
**Summary**
Moving from October to Winter using composer.
138 out of 154 PHPUnit tests failing, all around Pivot.php:

ArgumentCountError: Too few arguments to function Winter\Storm\Database\Pivot::__construct(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php on line 351 and at least 3 expected

/var/www/html/vendor/winter/storm/src/Database/Pivot.php:45
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:351
/var/www/html/vendor/winter/storm/src/Database/Model.php:208
/var/www/html/tests/PluginTestCase.php:217
/var/www/html/tests/PluginTestCase.php:110
/var/www/html/plugins/HS/shop/tests/unit/BaseTestCase.php:36
/var/www/html/plugins/HS/shop/tests/unit/ProductAvailabilityTest.php:69

**Installed build**
Winter 1.1.3

Plugins

Drivers 1.1.3 - October
Currency 1.0.6 Responsiv Internet
Mix Helper 1.0.3 - Ompmega
Twig Extensions 1.2.7 - Vojta Svoboda
User 1.5.4 - Alexey Bobkov, Samuel Georges
Pages 1.4.5 Alexey Bobkov, Samuel Georges
Social Login 1.0.30 - Flynsarmy
Richeditor Snippets 2.1.5 - Tough Developer & inetis
Uploader 1.0.5 - Responsiv Internet
Contact Form 1.52.1 - Jan Vince
Blog 1.5.1 - Alexey Bobkov, Samuel Georges
Wysiwyg Editors 1.2.9 - Anand Patel
Debugbar 2.0.1 - Bedard
Shop 1.5.57 - HS
Resizer 1.2.0 - Aspen Digital
Small GDPR 1.12.1 - Jan Vince

**Steps**
- Follow steps to upgrade with composer from October to Winter at: https://wintercms.com/blog/post/how-start-using-winter-cms
- Run phpunit

**Comment by mjauvin** [comment]
Try copying the tests folder from the github repo

**Comment by avanns** [comment]
That's solved it, thanks so much for the quick reply!
