### ISSUE TITLE
Missing alias for Resizer class

### ISSUE THREAD

**Issue by RomainMazB** [wintercms/winter#252]
Originally raised by @DamsFX on Discord, the namespace for the Resizer class changed in October.

To keep compatibility with some important plugin (offline/responsive-images as an example), we may need to introduce an alias.

Related to https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/issues/78

A diffchecker between the new oc's file and the actual Winter's one.
https://www.diffchecker.com/EYX4huDL

**Comment by LukeTowers** [comment]
Not interested in doing this. That would be attempting to remain compatible with 2.0 which is an eternally moving goal post that's not worth it. If the plugin author doesn't want to support winter we can either fork the plugin or evaluate it for inclusion in the core, but I'm not liking the idea of changing the core to improve compatibility with one October plugin.

**Comment by RomainMazB** [comment]
That's fair and I'm not surprised by the answer: We should move on our way 👍🏼
