### ISSUE TITLE
Move scaffolding commands into System module

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#270]
### Package targeted

Both

### Description

Currently, the scaffolding commands in Winter CMS (`create:plugin`, `create:controller`, etc.) reside in the Storm library for historical purposes.

It may, however, make more sense for these to reside in the System module in Winter CMS, as these functions relate directly to Winter CMS functionality, and require a Winter CMS install to be used effectively. They would not be able to be used in isolation with the Storm library.

If accepted, I intend to put forward a PR that moves all the `create:*` commands into the System module, but leaving the base Scaffolding classes and Service Provider within the Storm library.

The main benefit of this change will be that we can write test cases for the scaffold commands, as currently these are not tested within the Storm library, ostensibly because it's impossible to load the plugin architecture within the Storm library tests.

### Will this change be backwards-compatible?

Mostly backwards-compatible, as most people will just use the commands directly, but it would break any custom implementations of these commands which may extend the original command.

**Comment by LukeTowers** [comment]
The theme commands should probably be moved to the CMS module then. Should we move the specific scaffolding commands into each applicable module? i.e.

System Module:
- plugin
- command
- model
- settings (when implemented)

Backend Module:
- Controller
- FormWidget
- ReportWidget

CMS Module:
- theme
- component

**Comment by bennothommo** [comment]
Yeah, I can definitely do it that way. I assumed we would just put them in System as those commands have traditionally been available at all times given that they've been provided by the Storm library, but it does make sense to make them only available if needed.

**Comment by LukeTowers** [comment]
Closed by https://github.com/wintercms/winter/commit/e3fecdb9c2df298970c963e14b8a7f3c47d15198
