### ISSUE TITLE
Attached image/s, in custom plugin, doesn't save reference in the system_files table

### ISSUE THREAD

**Issue by faselunare** [wintercms/winter#276]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

Pages, Users, Products (custom plugin)

### Issue description

In my custom plugin i have a model (products.php) which does not save references to the image and files in the database (system_files table). The images and files are uploaded correctly to the file system. 

This is a row in the db after the image upload where field, attachment_id and attachment_type are NULL

```
1 | 6122cea638a3c732992773.jpeg | 611a59db396f7099283423.jpeg | 37594 | image/jpeg | Faselunare Vega | Faselunare | NULL | NULL | NULL | 1 | 1 | 2021-08-22 22:24:38 | 2021-08-22 22:25:12
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

```

   
   

### Steps to replicate

Create new Product
Add title and image/files/images save the products

### Workaround

add
attachOnUpload: true to the image/images/files field but you need to create the product first, save and then add the attachments

**Comment by mjauvin** [comment]
I confirm this, just tested it with a plugin.

**Comment by faselunare** [comment]
I want to add that in the model table, there is no field with the same name as the relationship

**Comment by zaxbux** [comment]
Also experiencing this issue, the backend `fileupload` form field isn't being submitted with the create/save request (all other fields are).

**Comment by LukeTowers** [comment]
@zaxbux this should be fixed in https://github.com/wintercms/storm/commit/a644f69c8b7bb4b578e83f67bcaa03e605677f43, will release later today
