### ISSUE TITLE
Add support for setting the application key in .env files when running key:generate

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#29]
See:
- octobercms/october#5496
- octobercms/library#560
- octobercms/october#5514

**Comment by RomainMazB** [comment]
Ping @ericp-mrel, maybe you'd like to reopen the PR you've made on OC to fix this?

**Comment by ericp-mrel** [comment]
Yeah, I can re-create a PR since OctoberCMS rejected my changes.

**Comment by ericp-mrel** [comment]
PRs have been created. Let me know if there's anything I need to do or could improve in the PRs.

**Comment by LukeTowers** [comment]
Going forward (1.2+) .env files will be first class citizens in Winter so we no longer wish to support setting the application key in the config file by default. If someone has a legitimate need for it we can re-evaluate in the future but as of https://github.com/wintercms/storm/pull/40 the key:generate command is reverted back to mostly the Laravel default (exception is that it will generate a .env file if none exists).
