### ISSUE TITLE
Invalid security token and admin area is not opening just a blank screen

### ISSUE THREAD

**Issue by amjadniazi48** [wintercms/winter#312]
### Winter CMS Build

1.1

### PHP Version

7.3

### Database engine

MySQL/MariaDB

### Issue description

I getting the invalid security token issue on every browser just blank admin screen
with the following error in the console
```
Failed to load resource: the server responded with a status of 500 ()
modules/backend/assets/js/winter-min.js?v=1:1 Failed to load resource: the server responded with a status of 500 ()
framework.js?v=1:362 Uncaught ReferenceError: assetManager is not defined
    at Object.handleUpdateResponse (framework.js?v=1:362)
    at Object.success (framework.js?v=1:164)
    at c (jquery.min.js?v=1:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=1:2)
    at l (jquery.min.js?v=1:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?v=1:2)
```

### Steps to replicate

If login to the backend got invalid security token issue

**Comment by LukeTowers** [comment]
@amjadniazi48 what's the error you get when you go to modules/backend/assets/js/winter-min.js? Check your server logs to see what's up.

**Comment by amjadniazi48** [comment]
This is the error
<b>Parse error</b>:  syntax error, unexpected '?' in <b>/home/afinstitute/public_html/modules/backend/assets/js/winter-min.js</b> on line <b>524</b><br />

**Comment by bennothommo** [comment]
@amjadniazi48 which browser are you using?

**Comment by amjadniazi48** [comment]
using chrome

**Comment by amjadniazi48** [comment]
Its working perfectly ok on another server bluehost, donot know whats the problem

**Comment by amjadniazi48** [comment]
This error is also showing on both mozilla and chrome

**Comment by bennothommo** [comment]
@amjadniazi48 would you be able to provide the URL directly to the JS file if possible? It might be that the file is truncated or corrupted.

**Comment by amjadniazi48** [comment]
https://afinstitute.pk/modules/backend/assets/js/winter-min.js

**Comment by amjadniazi48** [comment]
showing these errors in console

`GET https://afinstitute.pk/modules/backend/assets/js/winter-min.js?v=1 net::ERR_ABORTED 500
backend:29 
GET https://afinstitute.pk/modules/backend/assets/js/winter-min.js?v=1 net::ERR_ABORTED 500
jquery.min.js?v=1:2 

POST https://afinstitute.pk/backend 403`

**Comment by bennothommo** [comment]
Unfortunately that means it is an issue with your hosting, not with Winter CMS. Perhaps there is an invalid server configuration or caching system at play. You will need to get in touch with your hosting provider to look into it.
