### ISSUE TITLE
Mail template HTML editor height bug

### ISSUE THREAD

**Issue by danielbozsoki** [wintercms/winter#322]
### Winter CMS Build

Winter version: 1.1.6

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

When editing a mail template, the height of the HTML editor is very small.

<img width="1366" alt="Képernyőfotó 2021-09-27 - 1 12 32" src="https://user-images.githubusercontent.com/13118726/134827381-50dd2312-171e-4d95-82b5-0c3a71120d25.png">

OK in full view.

<img width="1678" alt="Képernyőfotó 2021-09-27 - 1 13 01" src="https://user-images.githubusercontent.com/13118726/134827392-db105c36-7bd1-4eb1-a794-2381c41b7ab2.png">

### Steps to replicate

Just edit one mail template.

**Comment by bennothommo** [comment]
Thanks @bozsokidaniel - we'll take a look.

**Comment by bennothommo** [comment]
@bozsokidaniel What browser are you running? I'm unable to replicate this on Firefox 91.

**Comment by danielbozsoki** [comment]
@bennothommo I have tried on mac and windows also with Google Chrome version  94.0.4606.61 (64 bit) - latest version I think.

On Firefox seems to be good.

**Comment by bennothommo** [comment]
@bozsokidaniel I've tried Chrome 94 on Windows and Linux and it seems to be fine:

![image](https://user-images.githubusercontent.com/15900351/134905244-f96362fe-c64a-4c86-8b62-a173e8eb9222.png)

Could you use the Inspector Tool in your browser and find out if there's anything obvious as to why it's cutting off like that?

**Comment by danielbozsoki** [comment]
@bennothommo, I attach an Inspector Tool image in Google Chrome and Firefox side by side.

If I can see, the height of the div class="ace_content" doesn't match in this case, let's just say it's a difference for now. In Google Chrome (Windows) if I scroll I can see that the JS overwrites the values ​​of the height as well and it's fix 85px while in Firefox it's much bigger. Also the textarea is 17px height and it's also update-t by some JS. I'm not to say it’s a bug, but I think there can be something maybe.

![image](https://user-images.githubusercontent.com/13118726/134907910-fdfd53f4-f698-4a1d-a693-787947323494.png)

![scroll](https://user-images.githubusercontent.com/13118726/134909043-beb1965c-7cad-4e5d-b69a-d8f491d384ec.gif)

I will try to find some more information about this.

**Comment by bennothommo** [comment]
@bozsokidaniel thanks for the further info - it could potentially be an extension that you have running on Chrome that you may not have in Firefox?

**Comment by WebVPF** [comment]
I confirm. This problem exists.

**Comment by arvislacis** [comment]
Can confirm this on Linux, Brave browser (Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)).

I think that this may be related to issue I posted some time ago: https://github.com/wintercms/winter/issues/269

If you remove `stretch` class from `field-markdowneditor size-giant layout-relative stretch mode-tab` then it seems to work fine but this need to be confirmed and tested, I just did a simple test.

![2021-09-27_20-46](https://user-images.githubusercontent.com/626982/134959249-4e162cfe-db4c-4388-8fea-91aaa694907a.png)

**Comment by bennothommo** [comment]
I still can't replicate it, unfortunately, even on the OS's and browsers specified ☹️. Is it happening for a specific display resolution? Is there zooming applied in the browser?

**Comment by arvislacis** [comment]
I am personally using 1920x1080px display resolution but problem also persists when I resize window (and reload). Using default 100% zoom, no display scaling.

**Comment by arvislacis** [comment]
I can also confirm now that this is browser or engine specific problem as I have no problems in Firefox (on my Linux machine).
But on my Windows server Chrome browser I see the same issue again so probably something related to Chrome/Chromium browsers.

**Comment by bennothommo** [comment]
Thanks @arvislacis, I've been able to replicate it with a small window. Will look into it now :)

**Comment by bennothommo** [comment]
Alright, found the issue. It seems related to a `min-height` being applied to the `field-markdowneditor` element, when both the `stretch` and `size-giant` classes are applied - the minimum height in this case is set to 390px. If the editor is restricted below this min-height, the content gets cut off.

This only occurs in Chrome, Firefox seems to be unaffected.

**Comment by bennothommo** [comment]
@bozsokidaniel @arvislacis @WebVPF could you try the fix applied above in https://github.com/wintercms/winter/commit/7aea162fe2f383e800c29f8130c67c182e7573bd and let us know if that resolves the issue for you?

**Comment by arvislacis** [comment]
@bennothommo Fix works fine for me. :) Thanks.

**Comment by danielbozsoki** [comment]
@bennothommo checked, problem fixed on Mac and Windows with Chrome browser. Thanks! :)

**Comment by bennothommo** [comment]
Awesome news, thanks guys! Fix will be released with Winter 1.1.7!
