### ISSUE TITLE
Rainlab blog to Winter blog: wrong path aliasing when using blog post method inside a custom plugin

### ISSUE THREAD

**Issue by queengab** [wintercms/winter#323]
### Winter CMS Build

Other (please specify below)

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.blog, winter.page, own.plugin

### Issue description

I and good morning. 
I detected maybe a bug inside a wintercms method.

We had rainlab.pages and rainlab.blog installed on our instance.
We installed both winter versions, and following the cms messages removed the railab plugins.

We talked about this problem also on Discord. Maybe i hope it can help the community 

### Steps to replicate

Then we have a own plugin. 
Wintercms have aliased path so plugins that call rainlab plugin can continue to work .

Inside the `plugin.php` file we call by default on line 10 and 11
```
use RainLab\Pages\Classes\Page as StaticPage;
use Rainlab\Blog\Models\Post as BlogPostModel; 
```

and then a method on line 70-71
```
        BlogPostModel::extend(function($model) {
            $model->addJsonable('some_things');
```

Now if we leave as is, we receive a generic error `Class 'RainLab\Blog\Models\Post' not found`.

### Workaround

Changing perhaps 
`use Winter\Blog\Models\Post as BlogPostModel; ` works and website restart to work.

**Comment by bennothommo** [comment]
@queengab try running `php artisan cache:clear` inside your project folder from the command line. It could be that the `packages.php` inside the `storage/framework` directory is still referencing the old class. You could also try deleting this file manually which should then regenerate on the next page load.

**Comment by queengab** [comment]
Hi @bennothommo ,

thanks for your response.
Ok i had reporte my plugins with old references:

`use RainLab\Pages\Classes\Page as StaticPage;
use Rainlab\Blog\Models\Post as BlogPostModel; `

and if launch 
`php artisan cache:clear` receive the custom error: ` Class 'Rainlab\Blog\Models\Post' not found`

I have also search `storage/framework` but found only `services.php` and not `packages.php`

I remember you after i installed `Winter.blog` and `winter.pages` i made a php artisan `plugin:remove` of the rainlab one, but i have yet the blog articles so i think the db is still there?

**Comment by LukeTowers** [comment]
@queengab I'm closing this to clean up old tickets, feel free to reply confirming that it's still an issue on the latest version (v1.2) and I'll reopen it.
