### ISSUE TITLE
Issue with PHP 7.4.25 and media path, open_basedir

### ISSUE THREAD

**Issue by ivang76** [wintercms/winter#343]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

Error server side when opening a page that contains uploaded images.
**open_basedir restriction in effect, _file_ is not within the allowed path(s)**

### Steps to replicate

- Upgrade or switch to PHP 7.4.25 from any other older PHP version
- Open a page of a website tat contains images uploaded from backend that use the **|media** 

### Workaround

Not yet... I must rollover and back to previous php version

**Comment by bennothommo** [comment]
Unfortunately, that's a problem that you need to solve in your PHP config - that's not a Winter issue.

**Comment by bennothommo** [comment]
Check the `open_basedir` config in your new PHP version. Perhaps it has changed between versions.

**Comment by ivang76** [comment]
Hi again,
the open_basedir didn't change beetween version, but to fix the issue I must change it, adding the path "/storage/app" at the **open_basedir** param in the php.ini on all the sites.

I noticed this happens where has been used the twig ["| media"](https://wintercms.com/docs/markup/filter-media) to get the src of an image for a img tag, source coming from the old _octobercms_ version of these sites.

So, now I tried to edit the config/cms.php, removing a backslash from the media path related to the 'media' storage
`        'media' => [
            'disk'   => 'local',
            'folder' => 'media',
            'path'   => '/storage/app/media',
        ],` 

and the path became now: **path => storage/app/media**

This seams to fix the problem (and I have not to edit the php.ini anymore)... does this make sense to you @bennothommo ?
Before update all the sites I'd like to read a your thought and feedback about this point...

thanks

**Comment by bennothommo** [comment]
@ivang76 are you using symlinks at all between the old October version of the site and the new Winter one you're working on?

**Comment by ivang76** [comment]
@bennothommo probably yes, because the most of that sites are migrated from October... would it be a problem?
And how is that related to the php update too?

**Comment by bennothommo** [comment]
@ivang76 I'm not quite sure why the PHP update would present different behaviour, but I know that if you have open_basedir restrictions, then symlinks would never work if those symlinks go outside of the restricted directories.
