### ISSUE TITLE
Infinite loop when trying to impersonating other administrator users

### ISSUE THREAD

**Issue by lex0r** [wintercms/winter#357]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

If I'm an administrator (but not a super-user) who wants to impersonate another administrator (not a super-user either but also less privileged) I would expect this to be possible. For example, I could be an editor in chief wanting to impersonate a writer on my team, and we are both "administrators" but I'm a more privileged one.

Currently this is not possible. There's an infinite loop of calls hasAccess > hasPermission > getMergedPermissions > hasAccess in case the impersonator is not a super-admin.

### Steps to replicate

Initial setup:
Two administrator user with two roles exists: user A (role AR) and user B (role BR). AR has more permissions compared to BR, one of them is permission to impersonate. None of the administrator users are super-admins.

Steps:
1. Login as A
2. Locate B and try to impersonate

Expected result:
A starts to impersonate B.

Actual result:
An infinite loop leading to out of memory error. 

### Workaround

Make the impersonator a super-user.

**Comment by LukeTowers** [comment]
Just ran into this one and boy oh boy was it a giant pain to identify the issue as this on Homestead; can't believe you've put up with it since November. Fix will be pushed shortly.
