### ISSUE TITLE
Custom stylesheet editor throws wrong errors

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#376]
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate

### Issue description

Noticed at `Customize backend -> styles` that the error messages displayed are wrong.
At first I thought it was a CSS file.
But apparently it supports SCSS and it throws errors (but it still works)
![image](https://user-images.githubusercontent.com/89913092/145796408-796ae1f5-7586-4edb-a8e3-895af5ae54ba.png)

### Steps to replicate

add scss in `Customize backend -> styles`

**Comment by LukeTowers** [comment]
Yeah, at some point we're looking to replace the usage of Ace Editor with Monaco (the editor used by VS Code) which will probably solve those sorts of issues. Going to close this as I don't personally plan on doing anything to address this at the moment, but if anyone else is interested in making a PR (to either fix this or replace Ace with Monaco) then I'd be happy to reopen it.

**Comment by LukeTowers** [comment]
Might be as simple as changing the language used for that field from CSS to SCSS btw, feel free to try that and report back.

**Comment by AIC-BV** [comment]
> Might be as simple as changing the language used for that field from CSS to SCSS btw, feel free to try that and report back.

Yeah changing the language to scss solves the problem!
