### ISSUE TITLE
Plug-in not working

### ISSUE THREAD

**Issue by justbobtn** [wintercms/winter#395]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

jan-vince.SmallContactForm

### Issue description

Getting the following error when I try to submit:

"AJAX handler
'contactForm: onMailSend' was
not found." on line 753 of /home/
**********/public_html/
modules/cms/classes/
Controller.php

I’m using the latest version of WinterCMS.

### Steps to replicate

Fresh install of plug-in will not work. Get the above error when trying to submit the form.

**Comment by AIC-BV** [comment]
Did you add the component to your page?
CMS -> open your page -> components -> click on the component for the contactForm

Looks something like this when you added it
![image](https://user-images.githubusercontent.com/89913092/148202910-238c8309-321e-4d68-85ec-3fc6b2e22cd9.png)

**Comment by justbobtn** [comment]
I do have the component on the page.

**Comment by LukeTowers** [comment]
Please share the full contents of your page file that this is not working on or share a link to a winter instance with the problem demonstrated on github. Sounds like user error to me.

**Comment by justbobtn** [comment]
I got it to work. Upgraded to latest version (was 2 behind), removed and reinstalled the plug-in and it works now. Thank you!
