### ISSUE TITLE
When there is an index.html in the root, the backend loads it.

### ISSUE THREAD

**Issue by qroft** [wintercms/winter#402]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

I just installed a totally new WinterCMS via the Web-Installer on a Hetzner Wehost server for a client.
The webspace initially only had an index.html file in its root (A "Welcome, this webspace is under construction"-like).

Now after going through the whole installatin process, the packend shows me said index.html in the main window part of the Winter CMS backend.
I can see the whole backend top menu but when i click on dashboard, the page loaded beneath the menu is the index.html from the webhost.
When i click on "CMS", the side panel with Pages, Partials, Layouts etc. appears, but to its right i get the index.html

### Steps to replicate

1. Create an index.html with whatever content you want and put it into your root.
2. Upload the Winter CMS web installer index.php and its sub folder to the root.
3. Install Winter CMS
4. After finishing go to the backend and log in
5. You should see your index.html in the main window of the admin backend.

### Workaround

I simply deleted the index.html and everything works fine.

**Comment by LukeTowers** [comment]
That's very bizarre, sounds like a server configuration issue that prefers index.html over index.php. Will close for now but if anyone can reproduce it on other hosts / environments feel free to ping me

**Comment by josephcrowell** [comment]
The web server would do this by the host's configuration. I has nothing to do with Winter's backend.
