### ISSUE TITLE
[Enhancement] Add winter:deploy command

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#427]
This will be a collection of various ideas around static file generation & deployment of assets to CDNs.

Ideas:
- Add support to the `winter:mirror` command to publish a filtered list of assets (i.e. only assetExtensions and potentially excluding local file storage folders)
- Build caching plugin that generates static files that the server software can then handle the routing for with 404 falling back to Winter for any dynamic routes

Further ideas and discussion welcome

**Comment by bennothommo** [comment]
Personally, I believe deployment is too opinionated to be something we can truly include in core, so perhaps this command should be something along the lines of `winter:static`?

**Comment by LukeTowers** [comment]
Yeah, I'm pretty flexible about what it would be called, @jaxwilko was working on making Winter work on Laravel Vapor and as part of their deployment process they copy everything from the public folder to a S3 bucket and change the asset_url to the CDN URL for the bucket and I thought that would be a pretty nice thing that we could potentially do in the core as well.

The static file generation for caching of route responses is something else that I've been thinking about for a while so thought I'd include it here for discussion.

**Comment by bennothommo** [comment]
Both great ideas definitely, I just personally don't want it to sound like the "one true method"(tm) of deployment.
