### ISSUE TITLE
Improve developer tools for localization on the client side

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#436]
At this stage, translations for the plugin are useless. It is controlled from javascript.
Here are all the script lines that need to be localized:

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L314

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L401

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L453

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L459

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L496

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L565

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L683

https://github.com/wintercms/wn-notes-plugin/blob/f9937edf69e078127276d2ee5aca1a9cca59337f/formwidgets/notes/assets/js/notes.js#L731

**Comment by bennothommo** [comment]
Wouldn't precompiling it to a file still require it to be brought in through AJAX? Or are you talking about generating a file somewhere and loading that in a link tag or something?

**Comment by LukeTowers** [comment]
I'm talking about generating a file somewhere and loading that in a link tag yes. We could potentially look at leveraging the Asset Compiler functionality to add support for loading combined localization files in somewhat the same way we do for existing JS / CSS files. We could also look at revising that functionality somewhat to bring it more in line with the ImageResizer's deferred compilation / compiling to static serveable asset files.

**Comment by bennothommo** [comment]
I'd prefer if it were something we could do without a command. I think with most of our command usage at the moment, it's been something for actual development on Winter itself (although I'll give that Snowboard / the mix commands will blur this line).

I'd be happy with the Asset Combiner handling it if it does the compilation in a way similar to the CSS / JS compilation - compiling it on the first use as required, then using the cache for all subsequent requests.

**Comment by LukeTowers** [comment]
Brain dump for reviewing later:

Some options out there:
- https://kazupon.github.io/vue-i18n/
- https://stackoverflow.com/questions/55957319/how-to-call-vue-i18n-from-non-vue-class
- https://phrase.com/blog/posts/the-best-javascript-i18n-libraries/
- https://github.com/airbnb/polyglot.js
- https://airbnb.io/polyglot.js/
- https://github.com/globalizejs/globalize
- https://medium.com/@jamuhl/vue-js-from-internationalization-i18n-to-localization-l10n-and-back-again-c3e5f7cc5e71

**Comment by bennothommo** [comment]
Oooo, I like Polyglot. Might be worth wrapping that for Snowboard.

**Comment by joseph-sm** [comment]
@LukeTowers We are most likely be looking at this shortly, in past projects we using packages that compiled a json file from the laravel translation files which was then added to webpacked javascript and vue-i18n, this does increase the bundle size but at least makes all the translations available in javascript, I can see how this would get messy with plugins and modules.

Not all the plugins use webpack.mix so the above way would not be possible very easily, so basically if a plugin / module has a lang folder would it just make a json / javascript file and combine that in asset generation per plugin / module?

**Comment by LukeTowers** [comment]
That's the general idea @joseph-sm, although the idea is for the language files to not be bundled with anything else, just be their own separate cacheable files.
