### ISSUE TITLE
[MediaManager]: Switch to using the ImageResizer class to generate thumbnails

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#437]
The MediaManager widget currently uses custom thumbnail generation logic implemented in `generateThumbnail()` and related path generation methods to generate the thumbnails for the media library items.

This causes the following problems:
- Generating thumbnails is only possible on deployments with active local storage (read-only filesystems cannot generate thumbnails)
- Resizing logic is unnecessarily duplicated

That logic should be revised to use the `ImageResizer` class as much as possible. Additionally the `ImageResizer` class may need to be double checked for functionality on read only filesystems.

Fixing this will improve our support for serverless deployment environments (i.e. Laravel Vapor).

**Comment by multiwebinc** [comment]
Probably related to this bug, but when you use `ImageResizer` to resize the images, it puts them in `storage/app/resized` (and keeps the original filename), but when resizing with Twig, (e.g. `{{ image|media|resize(width, height) }}`), it puts them in `storage/app/uploads/public` (and uses 9 hex characters for the path plus the resize parameters used as the filename). I would think that all resized images would be better in `storage/app/resized` and retaining the original filename. However, I like how the resize parameters are used in the filename when resizing with Twig.

**Comment by LukeTowers** [comment]
@multiwebinc nope, that is an intentional part of the design. What is actually happening is that when you pass a File model to the ImageResizer, it resizes with the File model's getThumbnail() functionality which stores the image the uploads folder allowing it to respect the public vs protected properties of File models. Any other source for an image will be handled with the ImageResizer's logic, storing it in the `/storage/app/resized` directory.

**Comment by LukeTowers** [comment]
Implemented in https://github.com/wintercms/winter/pull/596
