### ISSUE TITLE
Pivot fields in models list not showing if deferredBinding is set to true in relation_config.yaml

### ISSUE THREAD

**Issue by gianluca-ugolini** [wintercms/winter#458]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

Builder, Debugbar, User

### Issue description

If a Relation controller is defined with deferredBinding: true in yaml file, pivot columns are not shown in list table.

This image shows the config_relation.yaml file where relation has deferredBinding: true
<img width="579" alt="deferred-binding-true-relation-yaml" src="https://user-images.githubusercontent.com/13046806/154683709-f79f77a7-b045-40c5-a4d5-d6c9ac8346ca.png">

And the result in Related model update screen
<img width="3067" alt="deferred-binding-true" src="https://user-images.githubusercontent.com/13046806/154683748-e2839eb7-b948-44f0-a1f4-0d0d1b21ef0f.png">

This image shows the config_relation.yaml file where relation has deferredBinding: false
<img width="540" alt="deferred-binding-false-relation-yaml" src="https://user-images.githubusercontent.com/13046806/154684053-1b82be08-4112-42bb-abc7-3d32532739d8.png">

And the result in Related model update screen
<img width="3072" alt="deferred-binding-false" src="https://user-images.githubusercontent.com/13046806/154684425-70540c48-3af3-4c04-aa20-4ec932ede436.png">

Pivot columns are properly added to related pivot model's columns.yaml file
<img width="291" alt="columns-yaml" src="https://user-images.githubusercontent.com/13046806/154685946-9dc91d0c-0e44-4192-91f5-00eeec6abb40.png">

### Steps to replicate

Create three models:
 - Model A (id - name)
 - Model B (id - name)
 - Pivot Model C (id - model_a_id - model_b_id - pivot_extra_1 - pivot_extra_2)

In Model A and B set the BelongToMany relationship using model c pivot table data as shown in the documentation
https://wintercms.com/docs/database/relations#many-to-many

Create a controller for Model A and set up the relation controller behavior like this in config_relation.yaml

model_c_pivot_model:
    label: Model C
    view:
        list: ~/plugins/plugin-name/models/pivot-model-c/columns.yaml
        showSearch: true
    manage:
        list: /plugins/plugin-name/models/model-a/columns.yaml
    pivot:
        form: ~/plugins/plugin-name/models/pivot-model-c/fields.yaml

Add pivot columns to models/pivot-model-c/columns.yaml

id:
   label: ID
name:
  label: name
  searchable: true
pivot[pivot_extra_1]:
  label: Pivot 1
pivot[pivot_extra_2]:
  label: Pivot 2

In model A update screen, the relation controller list will show pivot columns only if deferredBinding is set to false (or unset).

**Comment by LukeTowers** [comment]
Darn bot is too fast for weekends 😝

**Comment by LukeTowers** [comment]
@gianluca-ugolini is this still an issue?

**Comment by gianluca-ugolini** [comment]
Yes, last check on v 1.1.9

**Comment by LukeTowers** [comment]
@gianluca-ugolini can you try on v1.2.1?

**Comment by gianluca-ugolini** [comment]
I confirm the bug is stille present.
Replicating the first example in 1.2.1

This is the result using deferred_binding: true
<img width="3079" alt="Schermata 2022-10-28 alle 15 34 36" src="https://user-images.githubusercontent.com/13046806/198614787-e8a7726d-0476-48aa-8cb2-487beb8ac7a3.png">

This is the result using deferred_binding: false
<img width="3077" alt="Schermata 2022-10-28 alle 15 37 32" src="https://user-images.githubusercontent.com/13046806/198621481-d648202c-04e7-4d7b-b91d-01fb0dead1a5.png">




It also seems that deferred binding have stopped working.
I try to add a status to a project that does not exists using deferred_binding:true and this is the result
<img width="3085" alt="Schermata 2022-10-28 alle 15 31 31" src="https://user-images.githubusercontent.com/13046806/198612967-a8616a23-ba37-4517-84c7-e596c74b937f.png">

<img width="483" alt="Schermata 2022-10-28 alle 15 31 48" src="https://user-images.githubusercontent.com/13046806/198613028-c3d81f2b-7c53-4056-b6ae-8584c1ae7786.png">

**Comment by LukeTowers** [comment]
In order for deferred binding to work correctly @gianluca-ugolini the column for the relationship that is being deferred must be marked as nullable in your table migrations, otherwise the DB itself expects a value to be present and the deferred binding system can't do its job.
