### ISSUE TITLE
Select2 does not load i18n localizations

### ISSUE THREAD

**Issue by dragomano** [wintercms/winter#461]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

Builder

### Issue description

Select2 dropdown library does not load i18n localization (e.g., message "No results found" during search in the list - it should be localized)

### Steps to replicate

1. Use a dropdown field with non-English localization
![](https://user-images.githubusercontent.com/229402/154752539-e8ca5375-e415-4ff3-aa5a-7e321bd2b41e.png)

**Comment by hauzmann** [comment]
Did you put this code in your plugn.php?

     // Listen for `backend.page.beforeDisplay` event and inject js to current controller instance.
    `  Event::listen('backend.page.beforeDisplay', function($controller, $action, $params) {
        $controller->addJs('/modules/system/assets/ui/vendor/select2/js/i18n/ru.js');
    });`

Everythig works fine for me:
![select2](https://user-images.githubusercontent.com/45749455/154814377-c265e590-ce9e-46bb-b2ec-5e4c44f83b4a.png)

**Comment by dragomano** [comment]
Thanks. It would be better to add it once in `/modules/backend/classes/Controller.php`:

```php
// Listen for `backend.page.beforeDisplay` event and inject js to current controller instance.
\Winter\Storm\Support\Facades\Event::listen('backend.page.beforeDisplay', function($controller, $action, $params) {
    $controller->addJs('/modules/system/assets/ui/vendor/select2/js/i18n/' . Config::get('app.locale') . '.js');
});
```

**Comment by LukeTowers** [comment]
This should definitely be handled by the code that already loaded client side localizations for the Winter backend; a PR would definitely be appreciated :)
