### ISSUE TITLE
Taglist in relation mode don't support default values

### ISSUE THREAD

**Issue by PubliAlex** [wintercms/winter#467]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

SQLite

### Issue description

When you have a taglist in relation mode, you can't set default values.

### Steps to replicate

- Create 2 models, with a manyToMany relationship between them (eg : Post and Author)
- In post model, add that field in your fields.yaml
        authors:
        label: Authors
        type: taglist
        mode: relation
        nameFrom: lastname
        placeholder: Please choose
        default: [1]
- Create an Author entry, make sure it's id is = 1
- Create a Post entry, you will see that the Author taglist is empty instead of seleting the Author you just created

I also tried to extend Post form fields and model like this : 

    public function formExtendFields($form) {
        if($form->getContext() == 'create') {
            $form->getField('title')->value = "Test"; // work
            $form->getField('authors')->value = ['1']; // don't work
            // $form->getField('authors')->value = ['Doe']; // don't work
        }
    }

Also tried this : 

    public function formExtendModel($model) {
        if ($this->formGetContext() === 'create') {
            $model->title = 'Super'; // Work
            $author = Author::findOrFail(1);
            $model->authors->push($author); // Dont work
        }
    }

In both case, I tried to reproduce the $form or $model object compared to the ones I dumped when editing existing Post. Each time, the Authors taglist is empty.

Thank you

Alex

**Comment by mjauvin** [comment]
@PubliAlex try this patch, it fixes the TagList formwidget behavior with default value:
```diff
diff --git a/modules/backend/formwidgets/TagList.php b/modules/backend/formwidgets/TagList.php
index 0bdc0c13c..63a65ae9d 100644
--- a/modules/backend/formwidgets/TagList.php
+++ b/modules/backend/formwidgets/TagList.php
@@ -154,7 +154,7 @@ class TagList extends FormWidgetBase
         $value = parent::getLoadValue();
 
         if ($this->mode === static::MODE_RELATION) {
-            return $this->getRelationObject()->lists($this->nameFrom);
+            return $value ?: $this->getRelationObject()->lists($this->nameFrom);
         }
 
         return $this->mode === static::MODE_STRING
```

Note: the diff above is against wip/1.2 branch, so line numbers could be different.

**Comment by PubliAlex** [comment]
You...... are....... the........ boss, works perfectly !

**Comment by LukeTowers** [comment]
We'll leave it open for now until the fix is merged @PubliAlex, but thanks for confirming it works!
