### ISSUE TITLE
winter:down doesn't seem to drop indexes along with tables

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#473]
In a fresh Winter CMS installation that has all of the Winter.* first party plugins present, running `winter:up` and then `winter:down` and then `winter:up` again (on SQLite anyways) will reveal that the indexes for removed tables were somehow left behind
<img width="1714" alt="Screen Shot 2022-02-24 at 7 18 06 PM" src="https://user-images.githubusercontent.com/7253840/155635176-4c1506b2-7f26-4839-9bf3-734210b8334e.png">
.

**Comment by bennothommo** [comment]
@LukeTowers I just tried this and didn't encounter the issue. I had installed Pages, Blog, User, Forum, Sitemap, Translate. Was there any other plugins you had in there too?

**Comment by LukeTowers** [comment]
This is on 1.2 using SQLite. I also have most of my personal plugins present but none of them interact with the blog plugin AFAIK.

**Comment by bennothommo** [comment]
I tried both 1.1 and 1.2 and it appeared to work fine. :/

**Comment by LukeTowers** [comment]
Huh, I'll see if I can replicate on a fresh install sometime

**Comment by bennothommo** [comment]
@LukeTowers feel free to re-open this if you manage to replicate it. :)
