### ISSUE TITLE
Menu item not set as active

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#478]
### Winter CMS Build

dev-develop

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.staticPage

### Issue description

Winter.staticPage menu don't set item as active if his pointing to a 'CMS page' with `url = "/"` configuration.

### Steps to replicate

Add a CMS page with this configuration in the active theme : 
```
title = "Welcome"
url = "/"
layout = "default"
```

Add a reference to this home page in a Winter.staticPage menu : 
- Type of the menu item 'URL', url value '/' => menu item is maked as active
- Type of the menu item 'CMS page' referencing the Welcome page => menu item is NOT maked as active

**Comment by LukeTowers** [comment]
Fixed in https://github.com/wintercms/winter/commit/3cf4b5a5cbb29fbf415601ce944532e9f3dbc685
