### ISSUE TITLE
registerNavigation sidemenu counter 0 is displayed

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#483]
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate

### Issue description
![image](https://user-images.githubusercontent.com/89913092/157061476-b863056d-0bc4-4579-8045-cdbfa9b9c5ed.png)
When counter is 0 it should not be displayed?

### Steps to replicate

```
public function registerNavigation()
    {
        $orders = Orders::where('status', 0)->count();
        
        return [
            'account' => [
                ...
                'counter'     => $orders + $x + $y, // (IF 0, IT IS NOT DISPLAYED HERE)

                'sideMenu' => [
                    'orders' => [
                        ...
                        'counter'     => $orders, // (IF 0, IT IS DISPLAYED)
                    ]
                ]
            ]
        ];
```

### Workaround

```
$orders = Orders::where('status', 0)->count();
if ($orders == 0) $orders = null;
```

**Comment by bennothommo** [comment]
@AIC-BV @wintercms/maintainers what are your thoughts on the inconsistency here?

In my opinion, a "zero" should be displayed in both locations if set, and it should only be a `null` value that hides it (or perhaps also an empty string). Zero *can* be a valid value worth showing for a counter and `null` more explicitly describes the absense of a counter.

**Comment by LukeTowers** [comment]
This is performing as designed. I added "empty" logic to hide counters when the value was zero specifically when using a callable counter (see https://github.com/wintercms/winter/commit/cb878020806ff4b64d23ea4d1d138350b695df3b) since returning null instead of 0 from a callable would probably cause issues with other code wanting to use that callable; but as stated in the workaround if an explicit integer is provided as the value of the counter then it is the responsibility of the developer providing that value to handle the 0 case.

**Comment by AIC-BV** [comment]
If it is meant to behave like this, then its fine by me 😄
Easy workaround!

It's just seemed like a bug because at the top navigation bar it doesn't show the 0 label
![image](https://user-images.githubusercontent.com/89913092/157188678-4f478236-6438-4e57-9da4-7ebb6640193e.png)

**Comment by LukeTowers** [comment]
@AIC-BV that's because the top menu bar is a calculated value by default, if you manually specified `0` as the value for the counter in the top menu bar instead of leaving it unset then it should display `0` as well.

**Comment by AIC-BV** [comment]
> @AIC-BV that's because the top menu bar is a calculated value by default, if you manually specified `0` as the value for the counter in the top menu bar instead of leaving it unset then it should display `0` as well.

If I'm not mistaken, it doesn't display the 0
```
'account' => [
                'label'       => 'Orders',
                'url'         => Backend::url('aic/account/orders'),
                'icon'        => 'icon-shopping-cart',
                'permissions' => ['aic.account.*'],
                'order'       => 500,
                'counter'     => 0,
```

**Comment by LukeTowers** [comment]
Huh. Well if someone wants it to display the 0 I'm fine with a PR that makes the behaviour align with the sideMenu counter behaviour. I probably won't touch it otherwise though.
