### ISSUE TITLE
Unable to install via backend

### ISSUE THREAD

**Issue by joho1968** [wintercms/winter#509]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

Trying to install a new theme (any theme) while testing Winter, I keep getting this error message:

```
Update failed
File from server is corrupt.
```

The "popup" is displayed, and things look like they're downloading. But very briefly after that, the error message is displayed.

It doesn't matter which theme I try to download.

I see no errors in the php.log file (I have error_reporting set to E_ALL, and Winter is in debug mode).

### Steps to replicate

- Enter backend
- Go to Updates & Plugins
- Choose themes
- Pick any theme

**Comment by bennothommo** [comment]
This is not something we can control as of yet. The Backend of Winter still uses October's marketplace for downloading plugins and themes, and can break at any moment on the whims of the October maintainers.

Once our new Marketplace is online, we'll switch over these functions to use our Marketplace instead.
