### ISSUE TITLE
Unable to save a newly created page in the editor.

### ISSUE THREAD

**Issue by shadow5og** [wintercms/winter#523]
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

Unable to save a new page. Instead, I get a pop up modal with HTML in it.

![image](https://user-images.githubusercontent.com/55452673/161461351-62d2f427-978b-4074-9695-853a69316828.png)

### Steps to replicate

Create a new page with no layout selected, paste HTML from an already done page where styles are in the HTML, this includes the head tag, and then try to save. The funny modal will pop up.

**Comment by LukeTowers** [comment]
@shadow5og are you or your host using ModSecurity rules? See https://octobercms.com/support/article/ke-1

**Comment by shadow5og** [comment]
Hello Brother

Yes, my host does use mod security.
Let me check the attached.

**Comment by shadow5og** [comment]
Disabling Mod Security does indeed solve the problem. Thank you.
