### ISSUE TITLE
Snowboard.js isn't picking up on the CSRF token automatically in the backend

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#541]
When making a request via Snowboard in the backend it will always fail with invalid token errors because it is not automatically including the CSRF token from the meta tag in the head.

**Comment by bennothommo** [comment]
@LukeTowers looks like it is using an AJAX pre-filter for this on the Backend:

https://github.com/wintercms/winter/blob/develop/modules/backend/assets/js/backend.js#L9-L16

We could perhaps rewrite that file as a Snowboard plugin and provide both a Snowboard event as well as the original jQuery pre-filter.

**Comment by LukeTowers** [comment]
Sounds like a good idea to me, thanks!

**Comment by bennothommo** [comment]
I'm still on the homebound road for this project for the next couple of days. Will be able to take a look at this next week. Let me know if it's urgent though.
