### ISSUE TITLE
Flash message appears twice in the backend if loading a new page with pending flash messages

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#549]
<img width="585" alt="Screen Shot 2022-05-04 at 10 37 05 AM" src="https://user-images.githubusercontent.com/7253840/166729071-d971d44f-e389-49b7-95a8-b63a2273cf28.png">

Edit a record and hit save & close. This will set a flash message in your session that the page load flash handler will render but for some reason it's also being rendered by the AJAX flash handler. 

@bennothommo would this have anything to do with the recent addition of Snowboard to the backend? Only a problem in recent commits of 1.2 (possibly 1.1.9 as well)

**Comment by bennothommo** [comment]
@LukeTowers I deployed a fix for this a couple of days ago - https://github.com/wintercms/winter/commit/43d386958175b5530a6c56497234719cc75377ef.

It hasn't been merged in with the 1.2 branch yet, but has been fixed in the 1.1 branch.
