### ISSUE TITLE
Add feature to create component templates automatically in theme through the Backend

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#556]
### Package targeted

Winter CMS

### Description

Inspired by discussions on Discord (hat tip to "TinTong" on Discord).

It would be a nicety if we could allow users to create component partial templates automatically in the right location in their theme, to quickly jumpstart modification and customisation of the components. A simple button to create the templates in the theme would suffice - only allowing the templates to be created if they haven't already been done so.

I'm thinking this button can be in one of the two locations:

- The components list in the CMS menu, or,
- Within the component property editor (perhaps the heading portion).

We could even automatically open up the templates for editing, as the user in both cases will be in the CMS section and will have the tabbed interface open.

### Will this change be backwards-compatible?

Yes, this is a new function that won't affect any previous functionality. Users will still be able to manually create partial overrides if they wish.

**Comment by LukeTowers** [comment]
Isn't this sort of already supported by the "forking" functionality of the CMS editor?

**Comment by bennothommo** [comment]
Today I learned something, that this feature even exists! :P

It doesn't quite cover the use case I had in mind though. Besides the fact that it is very, very hidden, it only populates the contents of the `default.htm` partial in the editor. I'm wanting for **all** partial templates to be copied and brought over, so that they act as true overrides and the theme developer is able to modify partials that might be referenced within the default partial
