### ISSUE TITLE
Call to undefined method addVisible

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#567]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

custom

### Issue description

Winter CMS - 1.2

When I try to export, I get an error:

> "Call to undefined method WebVPF\Custom\Models\Item::addVisible()" on line 71 of www\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php

I do export according to the example from the official documentation https://wintercms.com/docs/backend/import-export#export-model

```php
class SubscriberExport extends \Backend\Models\ExportModel
{
    public function exportData($columns, $sessionKey = null)
    {
        $subscribers = Subscriber::all();
        $subscribers->each(function($subscriber) use ($columns) {
            $subscriber->addVisible($columns);
        });
        return $subscribers->toArray();
    }
}
```

### Steps to replicate

Export Implementation

**Comment by TheFehr** [comment]
I can confirm this.
My upgraded october code base has the same problem.

**Comment by bennothommo** [comment]
Laravel 7 dropped the `addVisible` / `addHidden` methods ([upgrade note here](https://laravel.com/docs/7.x/upgrade#blade-components-and-blade-x)) in favour of `makeVisible` / `makeHidden`. You can switch to those methods if you wish as a workaround, but we'll likely have to re-add these in as they were in our docs.

**Comment by WebVPF** [comment]
@bennothommo Thank you!
Replaced `addVisible` method with `makeVisible` method. The export worked.

~~$subscriber->addVisible($columns);~~

```php
$subscriber->makeVisible($columns);
```

**Comment by bennothommo** [comment]
Restored the `addVisible` / `addHidden` methods as of https://github.com/wintercms/storm/commit/1643791cc13fac0b9724e6cd095f12387f7ddfb2.
