### ISSUE TITLE
ViewMaker::makePartial() regression

### ISSUE THREAD

**Issue by mjauvin** [wintercms/winter#571]
### Winter CMS Build

Other (please specify below)

### PHP Version

8.0

### Database engine

Other (please specify below)

### Issue description

The commit that changed the default extension for backend partials from `.htm` to `.php` broke BC.

ref. 643a581ce93cc5f8efb3fc8a2420c8dc014c8787

### Steps to replicate

When calling the ViewMaker trait makePartial() method, the following worked in previous Winter versions:
```
$obj->makePartial('modules/backend/widgets/form/partials/field_dropdown', ...);
```

**Comment by LukeTowers** [comment]
Fixed in https://github.com/wintercms/winter/commit/7a25524f737b8c4a612f917900e0a276d43bd447
