### ISSUE TITLE
Mail branding - Settings page error

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#573]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

Winter CMS 1.2
Open the **Mail branding** page `/backend/system/mailbrandsettings`

> Object of class Winter\Storm\Foundation\Application could not be converted to string

![2022-06-11_140645](https://user-images.githubusercontent.com/61043464/173185298-b54e1797-ad26-46e4-8cb1-7a5517d6120f.jpg)

### Steps to replicate

Open the Mail branding page

**Comment by bennothommo** [comment]
Confirmed bug.

**Comment by arvislacis** [comment]
Isn't this somehow similar to https://github.com/wintercms/winter/issues/557 ?

**Comment by bennothommo** [comment]
Possibly - I had confirmed it on a fresh install without any plugins however.

**Comment by LukeTowers** [comment]
What version of twig are you using?

**Comment by WebVPF** [comment]
@LukeTowers Twig version 3.4.1
Could it be because `assetic/framework` require-dev ^2.11 ?
I did the transition to Winter 1.2 according to this guide https://github.com/wintercms/meta/blob/master/l9-upgrade-notes.md

Here are the mentions of the twig in my composer.lock
```json
"packages": [
        {
            "name": "assetic/framework",
            "version": "v3.0.1",
            "require-dev": {
                "twig/twig": "^2.11",
            }
       },
      {
            "name": "twig/twig",
            "version": "v3.4.1"
      },
      {
            "name": "winter/storm",
            "version": "dev-wip/1.2",
            "require": {
                "assetic/framework": "~3.0",
                "laravel/framework": "~9.0",
                "php": "^8.0.2",
                "twig/twig": "~3.0"
            }
        },
       {
            "name": "maximebf/debugbar",
            "require-dev": {
                "twig/twig": "^1.38|^2.7|^3.0"
            }
        },
        {
            "name": "symfony/http-kernel",
            "version": "v6.0.9",
            "conflict": {
                "twig/twig": "<2.13"
            },
            "require-dev": {
                "twig/twig": "^2.13|^3.0.4"
            }
        },
        {
            "name": "symfony/var-dumper",
            "version": "v6.0.9",
            "require-dev": {
                "twig/twig": "^2.13|^3.0.4"
            }
        },
```

**Comment by LukeTowers** [comment]
Closing in favour of https://github.com/wintercms/winter/issues/557
