### ISSUE TITLE
Improve handling of ConfigWriter class when using "winter:install"

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#60]
Refs: https://github.com/wintercms/winter/discussions/59 (reported by @dhawton)

Currently, `ConfigWriter` will throw parse errors when manipulating config files with `env()` calls within while running the `winter:install` command, as it does not properly parse the entire `env()` call when doing its replacement. We should try to improve the handling of `ConfigWriter` to account for this, perhaps by having it just overwrite the default value and leaving the `env()` call intact.

In addition, it would be a nice-to-have feature to have `winter:install` change the `.env` file if it exists from a `winter:env` call made previously. This would allow people to run `winter:env` then use `winter:install` to guide them through the process of changing the configuration in this file.

**Comment by LukeTowers** [comment]
This should be resolved with the ArrayFile enhancements added by @jaxwilko in v1.2
