### ISSUE TITLE
Version of build

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#607]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

After update:

> Detected a modified version of Winter CMS build 1.1.8

Should be 1.1.9

No change here https://github.com/wintercms/meta/blob/master/manifest/builds.json

### Steps to replicate

```bash
composer update
```

Then:

```bash
php artisan winter:version 
```

**Comment by LukeTowers** [comment]
So quick on the draw there @WebVPF 😜 Updating the builds.json file is a manual step of our release process, @bennothommo is currently working on it. There's a lot of things that have to happen in order to release a new version of Winter, let alone three new versions 😉

**Comment by bennothommo** [comment]
@WebVPF could you give it a try now and let me know what you get?

**Comment by WebVPF** [comment]
@bennothommo Now it shows correctly. Both in the console and in the backend widget.

> *** Detected Winter CMS build 1.1.9.

**Comment by bennothommo** [comment]
Thanks @WebVPF!

**Comment by WebVPF** [comment]
@bennothommo There is a problem with version 1.2

```
php artisan winter:version
*** Detecting Winter CMS build...
*** We could not accurately determine your Winter CMS build due to the number of modifications. The closest detected build is Winter CMS build 1.2.0.
```

I upgraded from dev to stable.
In the backend (widget and system/updates) it shows version 1.1.8

**Comment by WebVPF** [comment]
The person from the telegram chat did a new installation of Winter, writes that he has the correct 1.2.0

**Comment by bennothommo** [comment]
@WebVPF yeah might be something wrong with your instance there. I just did `composer create-project wintercms/winter winter "^1.2.0"` and got the following:

![image](https://user-images.githubusercontent.com/15900351/179217541-b36b905a-02e5-486a-adef-b9c18ffb4da6.png)

**Comment by LukeTowers** [comment]
@WebVPF can you run `artisan winter:version --changes` after running `composer update` again and post the list of changed files?

**Comment by WebVPF** [comment]
@bennothommo @LukeTowers 
version 1.2.2

**Comment by WebVPF** [comment]
@bennothommo
build 1.2.3

**Comment by bennothommo** [comment]
@WebVPF we've now set up GitHub Actions to automatically update the manifest when a new build is released, so hopefully, no more need for the reminders :smile:. Thanks for reminding us about them though.
