### ISSUE TITLE
Add mail template/layout/partial clear command

### ISSUE THREAD

**Issue by RomainMazB** [wintercms/winter#613]
### Package targeted

Winter CMS

### Description

As of today, when modifying a mail template, layout or partial from the backend settings, the views are saved in the database, and there is no easy way to clean up these views.
~~AFAIK we need to manually erase the corresponding table entries to retrieve the default registered view.~~
> Edit for this sentence 👆🏻: this could be achieved using the trash icon from the backend template update page.
Thanks to mjauvin that pointed this out on Discord

Many users doesn't even know that fact and think that using the `view:clear` or `cache:clear` commands will clear the cached mail view files.

I suggest to add a console command to do the trick, `mail:clear`:
- without any arguments, it would wipes all the three `system_mail_*` tables
- with the `--type=[template|layout|partial]` argument, it would wipes only the corresponding `system_mail_*` table
- with the `--code` argument which could handle wildcard like `--code=winter.system::*` or `winter.user::*`, it would wipes only the corresponding entries from the tables
- `type` and `code` arguments could be used together to target only the template of a plugin as an example

The command would add a warning message to make sure no accidental data loss is permitted like:
```terminal
Your are about to clear all the `winter.system::*` saved mail templates modification from the database, confirm [y/n]:
```

**Comment by LukeTowers** [comment]
What I would prefer is removing the reliance on the DB tables entirely, which we may be able to do now with the new ArraySource trait in Storm, and then making it so that only once a modification has been made to the defaults provided then that is when a value is stored in the database and it becomes the new version loaded when the system is asked for that particular mail template object. @bennothommo @jaxwilko @mjauvin any thoughts?

**Comment by mjauvin** [comment]
I thought that's how it was already.

**Comment by LukeTowers** [comment]
Archiving for now, anyone who runs into this in the future feel free to comment and we can reopen it then.
