### ISSUE TITLE
[v1.2] PHPUnit.xml file from docs does not work

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#615]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

No database

### Issue description

`php artisan winter:test` command throws an error when run with the phpunit.xml file from the [docs](https://wintercms.com/docs/help/unit-testing#testing-plugins) in a brand new plugin.

```bash
Cannot open file "[truncated]/plugins/bdx/toolbox/../../../tests/bootstrap.php".
```

### Steps to replicate

1. Create new Winter CMS project
2. Create new plugin (`php artisan create:plugin`)
3. Create phpunit.xml file in plugin directory, contents from [docs](https://wintercms.com/docs/help/unit-testing#testing-plugins)
4. Run `php artisan winter:test`

### Workaround

Replace the bootstrap="" line with the following contents. (Not sure if this is actually correct, but it works).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="../../../modules/system/tests/bootstrap/app.php"
         colors="true"
    ...
```

**Comment by ericp-mrel** [comment]
Moved to https://github.com/wintercms/docs/issues/88 since this is mostly a doc issue.

**Comment by LukeTowers** [comment]
@ericp-mrel thanks! For future reference we can move issues as admins on the organization in GitHub so we can make the move slightly nicer :)
