### ISSUE TITLE
create:theme tailwind error

### ISSUE THREAD

**Issue by ghost** [wintercms/winter#619]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

none

### Issue description

Clean install Winter CMS v1.2.0, with Composer v2.3.8 on a Linux laptop (Pop! OS 22.04 LTS ).
When I want to create a Tailwind theme `php artisan create:theme test tailwind`I get an error.
**Error** In Filesystem.php line 57: `file does not exist at path /home/ben/Code/Sites/wn-test/modules/cms/consol  
  e/scaffold/theme/tailwind/readme.stub.`

### Steps to replicate

`php artisan create:theme test tailwind`

### Workaround

Change `wn-test/modules/cms/console/scaffold/theme/tailwind/README.stub` to `wn-test/modules/cms/console/scaffold/theme/tailwind/readme.stub` (lowercase).

**Comment by LukeTowers** [comment]
Thanks for the report @ben-nl, should be fixed now.
