### ISSUE TITLE
Migrate October to Winter : Twig loadTemplate error

### ISSUE THREAD

**Issue by m-paniez9292** [wintercms/winter#627]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Romanov.ClearCacheWidget, Rjchauhan.LightGallery, Zen.Robots, Rahman.BlogTags, Flosch.Slideshow, Winter.Pages, Winter.Translate, Winter.User, Winter.Location, Winter.Notify, Winter.Sitemap, Winter.Blog

### Issue description

Hi,
I try to migrate an 1 page website (build with Pages and blocks).

After a composer upgrade (quick step), the frontend give me an error :
`Too few arguments to function Twig\Environment::loadTemplate(), 1 passed in /home/www/XXXXX.com/www/plugins/winter/pages/classes/Controller.php on line 79 and at least 2 expected`

So, I go to the backend and it works : I change all Rainlab plugins to Winter plugins manually by plugin manager.
I have always the same error.

For me, `composer update` doesn't update twig and some other.

Thanks

### Steps to replicate

This website was build with the last v1 October

**Comment by mjauvin** [comment]
Latest version of Winter.Pages solves this issue.

What version do you have?

**Comment by m-paniez9292** [comment]
Re,

I have Winter.Pages v2.0.0 (I do all process today).

Thanks

**Comment by mjauvin** [comment]
You need version 2.0.2

**Comment by m-paniez9292** [comment]
Re,
> You need version 2.0.2

That's right, it works.
For other, to do that : `composer require winter/wn-pages-plugin`
Just for curiosity, why the update method by backend > plugin > update doesn't work ?
Thanks

**Comment by bennothommo** [comment]
@m-paniez9292 the update functionality of the backend won't fully work until we have a marketplace.
