### ISSUE TITLE
Twig not recovered View::share()

### ISSUE THREAD

**Issue by Dreanad** [wintercms/winter#630]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Source : https://wintercms.com/docs/cms/content#content-global-variables

There seems to be a problem with twig to get the values in the View::share() function 

The View::share() function return the good value but can not be recovered by twig on the front 

### Steps to replicate

In the boot function juste add 
`       
 View::share('site_name', 'Winter CMS');
`

and in the layout or any page / partial dump the "site_name" variable, its returning null

**Comment by LukeTowers** [comment]
See https://github.com/LukeTowers/oc-essentialvars-plugin/blob/master/Plugin.php#L38-L77 for how to handle this in a more robust fashion. @bennothommo @mjauvin do you think it's worth updating the docs for this? I'm not sure what the underlying issue is, I know I ran into it ages ago when I wrote that plugin though.

**Comment by LukeTowers** [comment]
@bennothommo ping.

**Comment by bennothommo** [comment]
I'll have a look into why `View::share` doesn't work.

**Comment by bennothommo** [comment]
Hi all,

Sorry for the extreme delay on this.

So it seems that `View::share()` is used exclusively for static content (ie. content blocks, placeholders, etc.) and is run through the [`Winter\Storm\Parse\Bracket`](https://github.com/wintercms/storm/blob/develop/src/Parse/Bracket.php) bracket parser, which uses a single curly bracket (ie. `{site_name}`). It is *not* populated into the Twig variables.

I'm not sure if it should or not - I don't particularly see an issue for it to be available to the Twig environment as a default value that can be overridden by the page specifically defining a value, but happy to hear more thoughts on this. @LukeTowers @jaxwilko any thoughts?

I will note that this particular usage is defined on the Content Blocks page of the docs, so I think it was always intended to only be used there, but again, it could be extended out to Twig perhaps.

**Comment by LukeTowers** [comment]
I don't have a problem including them as default page variables.
