### ISSUE TITLE
Media manager error

### ISSUE THREAD

**Issue by quangtrongonline** [wintercms/winter#635]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.demo

### Issue description

After i installed Winter CMS on my vps, the media library crashed. But when I install it on localhost this error does not appear. My vps is using nginx. I tried looking for a workaround but I didn't find it. The thumbnail URL of the image is: /resizer/92dcd407477e7057e6d3195f7cc2dfe2c9bc6416/%252Fstorage%252Fapp%252Fresized%252Ffab%252Fa8d%252F0b8%252F236206431_153793693553284_7137375182485067657_n_resized_faba8d0b800696c76b004cb1111f31a57783a7b3.jpg
![Capture](https://user-images.githubusercontent.com/20581588/182889214-87fa0c1d-810d-47fc-8db0-ad90f3e444be.PNG)

### Steps to replicate

Install Winter CMS via composer -> Access to Media Library

**Comment by LukeTowers** [comment]
There's nothing to go off of here. Open the URL and see what the error message actually says and share it here please.

**Comment by quangtrongonline** [comment]
When i open the url i get 404 page

**Comment by LukeTowers** [comment]
Turn on debug mode and try again. With no detailed error message or other information to help you debug the issue there's nothing else I can do for you.

**Comment by quangtrongonline** [comment]
I have debug mode enabled. But there isn't any error message. I noticed when I use the |resize() filter on the frontend I get the same problem
![1](https://user-images.githubusercontent.com/20581588/182978017-f619a214-133e-4cd4-8010-b395fbc78456.PNG)

**Comment by bennothommo** [comment]
@quangtrongonline have you set up the Nginx config similar to our recommended Nginx config here: https://wintercms.com/docs/setup/configuration#nginx-configuration?

**Comment by quangtrongonline** [comment]
@bennothommo Yes I have configured url rewrite same as in your documentation

**Comment by quangtrongonline** [comment]
Oh i reconfigured url rewrite and it worked fine. my mistake was not reloading nginx. sorry for this omission. Thank you for your help
