### ISSUE TITLE
Infinity scroll on cms "pages" page

### ISSUE THREAD

**Issue by pavelmgn** [wintercms/winter#652]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.WnDebugbar, Winter.WnBuilder, Winter.WnDrivers

### Issue description

![cms_pages](https://user-images.githubusercontent.com/8817759/185204808-bd91c43b-e0ad-47f6-9dc6-199895a3c074.gif)

### Steps to replicate

Cms pages more than list block on pages list.
I have them with description.

### Workaround

Find in octobercms 2019 issues =) https://github.com/octobercms/october/issues/4621

**Comment by bennothommo** [comment]
@pavelmgn which browser are you running?

**Comment by pavelmgn** [comment]
> @pavelmgn which browser are you running?

@bennothommo Chrome 104.0.5112.102

**Comment by arvislacis** [comment]
Can confirm this also on Brave browser Linux - Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)

Of course this is only a minor issue and in standart cases users probably would not try to to trigger infinite scroll.

**Comment by bennothommo** [comment]
Yeah I have a feeling it's related to one of the jQuery plugins in use for mouse scroll / wheel handling - I do recall seeing this problem before but haven't for quite a while, so I had assumed it was just a browser quirk.

**Comment by pavelmgn** [comment]
If you round the height downwards, an object with the scrollbar-thumb class (for example: 151.847px > 151px) generated by the plugin will not have a problem =)
![image](https://user-images.githubusercontent.com/8817759/195639559-367f3e1f-43ec-401a-9d62-644f992bea07.png)
