### ISSUE TITLE
Add "Send password reset email" button to backend users update page

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#654]

**Comment by prsuhas** [comment]
@LukeTowers. Could you please provide some more details on this enhancement ? I would be glad to work on this enhancement.

**Comment by LukeTowers** [comment]
@prsuhas sure, would like there to be a button on the users update page in the backend, probably located under the Impersonate Users button that triggers the system to send the password reset email to the user in order to trigger a password reset manually. Is that enough information?

**Comment by prsuhas** [comment]
> @prsuhas sure, would like there to be a button on the users update page in the backend, probably located under the Impersonate Users button that triggers the system to send the password reset email to the user in order to trigger a password reset manually. Is that enough information?

Yes it would be sufficient to start with.

**Comment by LukeTowers** [comment]
Implemented in #723 by @prsuhas, thanks @prsuhas!
