### ISSUE TITLE
Route cache broken on winter 1.2

### ISSUE THREAD

**Issue by zawwz** [wintercms/winter#666]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Running `php artisan route:cache` breaks all routes.

HTTP requests return NotFoundHttpException and `php artisan route:list` returns "Your application doesn't have any routes."

### Steps to replicate

- Fresh install of wintercms
- Run `php artisan route:cache`

### Workaround

Clear the route cache by running `php artisan route:clear`

**Comment by bennothommo** [comment]
Confirmed.

**Comment by mjauvin** [comment]
@bennothommo should that be closed?

**Comment by bennothommo** [comment]
@mjauvin Nope, the PR is still open.

**Comment by mjauvin** [comment]
Didn't realize the PR was in storm...
