### ISSUE TITLE
Form widget of type text gets default attribute maxlength="255"

### ISSUE THREAD

**Issue by lex0r** [wintercms/winter#680]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When a widget of type "text" is rendered on the form by default it gets maxlength="255". This is too opinionated and leads to situations when a text field which is supposed to store very long string (and is not supposed to show it in full hence no textarea is used for it) silently truncates the provided (often via copy-paste) string and editors get no slightest idea their input has been trimmed.

I think it's reasonable to not define any limitation whatsoever by default. If anyone needs that they can do that by explicitly setting the attribute.

### Steps to replicate

Create a random form with a text input and insert a longer than 255 characters string in it. Then save and watch the string truncated even if the schema field it uses allows (or even expects) a lengthy string.

### Workaround

Explicitly define the maxlength with no value like below

`
            attributes:
                maxlength: ''
`

**Comment by LukeTowers** [comment]
I would agree that the default maxlength is somewhat arbitrary (I believe the intention behind it is to avoid SQL errors if inserting into a default VARCHAR(255) column, but that's not really a good enough reason to have it hardcoded in here).

Would you like to submit a PR to remove the offending line entirely?
