### ISSUE TITLE
[v1.2] CMS editor doesn't save all components added to page/layout/etc

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#683]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Pages

### Issue description

Adding multiple components to a layout/page from the CMS editor does not work, and only the last added component is saved to the actual file itself. All other components are lost.

### Steps to replicate

1. Install fresh winter cms project
2. Install Winter.Pages plugin
3. Add `static page` and `static menu` components to the default layout.
4. Save
5. View the `layouts/default.htm` file from your IDE/editor and see only one component is actually saved to the file.

### Workaround

Add components manually from your editor/IDE without using the backend.

**Comment by ericp-mrel** [comment]
Here's a video demonstrating the issue:
https://user-images.githubusercontent.com/63664924/189455663-85de653e-f1a2-4720-8eaa-8c50358b42a1.mp4

Another bug I noticed during this, you cannot remove components using the backend CMS editor either.

**Comment by willouch** [comment]
Same issues with php 8.1 and fresh install

**Comment by bennothommo** [comment]
Confirmed.

**Comment by bennothommo** [comment]
@ericp-mrel @willouch would you mind trying the fix in #686 and see if that resolves the issue for you?

**Comment by ericp-mrel** [comment]
@bennothommo, Seems to be working for me now with those changes.
The only issue that still remains, is not being able to remove components from layouts.

I just checked one of my older Winter CMS installations which is still running v1.1, the CMS still correctly adds/removes components from the backend. I'm kind of curious if the backend CMS portion for adding/removing components broke when Snowboard was introduced into the backend. That's the only thing I could think of that would've caused a change in behavior for backend JS.

**Comment by willouch** [comment]
its' working but new issue that still remains, is not being able to remove components from layouts.

**Comment by LukeTowers** [comment]
Snowboard is present in the 1.1 branch I believe so I'm not sure that would cause the issue. We'll need to figure out what commit caused the issue to come up with the ideal solution @bennothommo

**Comment by ericp-mrel** [comment]
I just found something that may be related. Using the add button from a relation widget and selecting all only adds the last item and not all of the selected items.

The `checked[]` array doesn't seem to get the full list of IDs, rather only the last selected ID.

![Screen Shot 2022-09-12 at 6 01 07 PM](https://user-images.githubusercontent.com/63664924/189772969-c13fd254-116b-4769-a459-79d4ed744921.png)


https://user-images.githubusercontent.com/63664924/189772931-2969ee20-4e8b-428f-a616-9d420edeb321.mp4

**Comment by bennothommo** [comment]
I think it might be related to this commit - https://github.com/wintercms/winter/commit/a4cfd0d23f4342f530dc4b425098ee24086cd8d1. There's likely something in those changes that doesn't support arrayed POST values.

**Comment by bennothommo** [comment]
I've deployed an updated fix here: https://github.com/wintercms/winter/pull/689. This should fix this issue as well as the one that @ericp-mrel reported in the relation widget.

Please feel free to re-test and let us know how you go.

Also, I wasn't able to replicate the issue where components could not be deleted in a layout. Seemed to work fine for me. Any more info on this will be appreciated.

**Comment by mjauvin** [comment]
@bennothommo open a layout in the CMS editor, add a component then save and close layout. reopen layout, delete component, save and close layout. reopen layout: component should still be there.

**Comment by bennothommo** [comment]
@mjauvin I was able to replicate this. It seems that with the layouts, changing only the components in a layout does not make the layout "dirty", and Halycon models on update won't trigger a save unless there is a dirty attribute. It's why it initially worked for me - the content in the code editor had changed ever so slightly (I think it removed a newline), which meant that the code attribute was dirty and thus it saved.

This issue in particular though is different to the issue reported in the OP, so I'd say we should probably split the component issue off into its own issue on GitHub.

**Comment by mjauvin** [comment]
@bennothommo do you mean create a new issue/PR for the component deletion problem on layouts?

**Comment by bennothommo** [comment]
@mjauvin yes please, let's create a new issue for the component deletion problem.
