### ISSUE TITLE
CMS Layout editor: cannot remove components.

### ISSUE THREAD

**Issue by mjauvin** [wintercms/winter#690]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When deleting a component from a layout within the CMS editor, the component persist after the layout is saved.

### Steps to replicate

- open a layout in the CMS editor.
- add a component then save and close layout.
- reopen layout, delete component, save and close layout.
- reopen layout: deleted component is still present.

**Comment by bennothommo** [comment]
[Comment in original thread:](https://github.com/wintercms/winter/issues/683#issuecomment-1245551499)
> I was able to replicate this. It seems that with the layouts, changing only the components in a layout does not make the layout "dirty", and Halycon models on update won't trigger a save unless there is a dirty attribute. It's why it initially worked for me - the content in the code editor had changed ever so slightly (I think it removed a newline), which meant that the code attribute was dirty and thus it saved.

**Comment by mjauvin** [comment]
@bennothommo this is still not resolved

**Comment by mjauvin** [comment]
Tested this again with latest develop branch and could not reproduce.
