### ISSUE TITLE
Remove the demo plugin and theme

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#693]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Demo

### Issue description

After a fresh installation of Winter, I run the command

```bash
php artisan winter:fresh
```

In the console I get the following message:

![2022-09-15_162230](https://user-images.githubusercontent.com/61043464/190415140-4fc6b21d-e877-4116-8a6a-ad8b80975947.jpg)

The demo theme is removed, but the demo plugin remains.

### Steps to replicate

After installation, run the command `winter:fresh`

**Comment by mjauvin** [comment]
Confirmed!
