### ISSUE TITLE
Missing uuid field on failed_jobs table

### ISSUE THREAD

**Issue by webbati** [wintercms/winter#696]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When job fail inserting it in the failed_jobs table require an `uuid` field that is not present in the table at the moment, so a pdo exception is thrown

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'field list' in /var/www/html/my.domain.it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82`

### Steps to replicate

see Mail queue is not instantiable https://github.com/wintercms/winter/issues/695

### Workaround

Add string field named 'uuid' to the failed_jobs table with a new migration

**Comment by LukeTowers** [comment]
@webbati do you feel like submitting a PR to add the necessary migration to the system module?

**Comment by webbati** [comment]
> @webbati do you feel like submitting a PR to add the necessary migration to the system module?

Sorry @LukeTowers, this week I have had some problems and I have not been able to do anything, not even about it. I see that it has already been done
