### ISSUE TITLE
Backend checkbox and switch fields no longer sent as boolean values

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/winter#706]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

It is no longer possible to save changes in the backend when using `boolean` validation rules on a model property with a `checkbox` or `switch` form widget.

This issue is related to the recent fix/changes introduced in this PR https://github.com/wintercms/winter/pull/689

If I install the latest version of the tagged v1.2.0 version of Winter CMS modules everything works as expected for boolean type values for checkboxes and switches. But, with the latest version of dev-develop this is no longer the case.

## Winter CMS v1.2.0 (tagged)

The tagged version of v1.2.0 sends the checkbox values correctly to the server.
<img width="827" alt="Screen Shot 2022-09-19 at 12 08 27 PM" src="https://user-images.githubusercontent.com/63664924/191074844-a2f9f379-ba1c-43e1-82e8-269a799a8355.png">

Here is what the value looks like in the `Backend\Widgets\Form->getSaveData()` class method:

![Screen Shot 2022-09-19 at 12 16 17 PM](https://user-images.githubusercontent.com/63664924/191075483-2aa13c41-08d0-43c9-bd41-300b0b623afb.png)

## Winter CMS dev-develop (commit e84933775d10bf48722e075096e6242c70f843b8)

But, this is how the current version of dev-develop is sending boolean checkbox values to the server and results in an array value rather than a single `true/false` or `1/0` value.

<img width="641" alt="Screen Shot 2022-09-19 at 12 09 06 PM" src="https://user-images.githubusercontent.com/63664924/191075041-1929ac2d-9237-4b46-95de-aca8ed5c2633.png">

Here is what the value looks like in the `Backend\Widgets\Form->getSaveData()` class method:

![Screen Shot 2022-09-19 at 12 16 30 PM](https://user-images.githubusercontent.com/63664924/191075609-d2a921e7-be24-4e9a-850b-24cbd834fb6b.png)

### Steps to replicate

1. Install the latest dev-develop branch of Winter CMS

2. Setup a backend form to use either a `checkbox` or `switch` form field.

3. Create a model and populate the `$rules` array with something like the following:
  ```php
class Example extend \Model
{
    public array $rules = [
        'is_active' => 'boolean',
    ];
}
  ```

4. Create the `fields.yaml` file for the model with the following contents:
```yaml
# fields.yaml

fields:
  is_active:
    label: Active
    type: checkbox
```

### Workaround

Revert to the v1.2.0 tagged version of Winter CMS.

**Comment by ericp-mrel** [comment]
I just want to add some slight clarification, checkbox and switch widgets send their values correctly when they are `unchecked` / `false` and it is only when they are set to `true` when the bug happens.

<img width="291" alt="Screen Shot 2022-09-19 at 12 34 51 PM" src="https://user-images.githubusercontent.com/63664924/191078759-ccdec2af-d304-448d-a5e2-ccdff26aae20.png">

<img width="294" alt="Screen Shot 2022-09-19 at 12 35 06 PM" src="https://user-images.githubusercontent.com/63664924/191078782-24e34709-5b84-46c0-9e11-c1aac57e9417.png">

**Comment by bennothommo** [comment]
@ericp-mrel thanks for the report. Should now be fixed by https://github.com/wintercms/winter/commit/2a4394b69088cc427885ecd6cbac76db6192919c.
