### ISSUE TITLE
Theme export failure: Undefined constant "Winter\Storm\Filesystem\GLOB_BRACE"

### ISSUE THREAD

**Issue by maoxuner** [wintercms/winter#714]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Blog, Winter.Pages

### Issue description

When export a theme, failed with error message
> Undefined constant "Winter\Storm\Filesystem\GLOB_BRACE"

### Steps to replicate

1. Go to theme manage page `cms/themes`
2. Select a theme and click manage button, then select export option
3. Select all directories to export(by default) and confirm
4. Undefined constant "Winter\Storm\Filesystem\GLOB_BRACE"

**Comment by LukeTowers** [comment]
> Note: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux.

See https://www.php.net/manual/en/function.glob.php.

Not sure what we can do instead here, @bennothommo @jaxwilko @mjauvin any ideas?

**Comment by maoxuner** [comment]
@LukeTowers That's right. I'm running on Alpine Linux

**Comment by bennothommo** [comment]
@LukeTowers if I recall correctly, Symfony does provide a glob polyfill. It's supposed to exist within the Finder component.

**Comment by maoxuner** [comment]
This comment may help

https://github.com/docker-library/php/issues/719#issuecomment-424145034

**Comment by LukeTowers** [comment]
@bennothommo https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Finder/Finder.php#L634 is the extent of their polyfill, I can't tell if that actually provides the same functionality or not. Any ideas?

**Comment by bennothommo** [comment]
Hmmm, doesn't appear to polyfill braces support, no.

Zend Framework does have a polyfill, but I don't want us to include an entire (deprecated) framework for one polyfill, so I suppose we either need to hunt for another one, or implement the polyfill ourselves.

**Comment by LukeTowers** [comment]
What are we even using it for? Is it just in the one place that we can remove that use and just implement the specific check in our code or do we need to build a proper polyfill into our library?

**Comment by bennothommo** [comment]
As far as I can tell, the only place we explicitly use it is the `Winter\Storm\Filesystem\Zip` class, which I assume is used for zipping up the theme export, but the underlying Filesystem class does support globs, which just forward through to the base `glob` method.

The Zip class uses it to include hidden files as an option - I'll have to see if it's something we can get around.

**Comment by bennothommo** [comment]
@pawmaster could you try the fix in https://github.com/wintercms/storm/pull/121 and let us know if that resolves the issue for you?

**Comment by maoxuner** [comment]
@bennothommo ~I'll have a try a few minutes later and then update this comment~
Good job. It works!
