### ISSUE TITLE
Route model binding does not appear to work in Winter 1.2

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#718]
### Discussed in https://github.com/wintercms/winter/discussions/717

<div type='discussions-op-text'>

<sup>Originally posted by **ericp-mrel** September 28, 2022</sup>
Hi,

I'm trying to use route model binding according to the Laravel documentation, but it is not working no matter what I do. https://laravel.com/docs/9.x/routing#customizing-the-key

I've tried doing something like this:
URL: `https://example.test/pdf/acme/my-slug/details` and `https://example.test/pdf/acme/1/details`
but I just get a new model instance, and it doesn't throw an exception if it can't find a record with the id/slug either.
```php
Route::get('/pdf/acme/{foo}/details', function (Foo $foo) {
// ...
});
```
and

```php
Route::get('/pdf/acme/{foo:slug}/details', function (Foo $foo) {
// ...
});
```

Just wondering if this is supported by Winter CMS? I assume it should be since this is just standard Laravel routing.</div>

**Comment by mjauvin** [comment]
I confirm this is not working with latest develop branch.

**Comment by mjauvin** [comment]
I also tested with 1.1.9 and it is not working either.

**Comment by mjauvin** [comment]
@ericp-mrel I found the issue... in order for the implicit model binding to work, you need to use the "web" group middleware in your route:
```
Route::get('/pdf/acme/{foo}/details', function (Foo $foo) {
    // ...
})->middleware('web');
```

Alternatively, you can use the `\Illuminate\Routing\Middleware\SubstituteBindings` middleware directly:

```
Route::get('/pdf/acme/{foo}/details', function (Foo $foo) {
    // ...
})->middleware('\Illuminate\Routing\Middleware\SubstituteBindings');
