### ISSUE TITLE
The uploaded logo from the backend doesn't respect the https protocol

### ISSUE THREAD

**Issue by haralake** [wintercms/winter#720]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

In the "customize backend" section of wintercms if I change the logo it doesn't appear either on the backend home page with credentials or on the dashboard.
![Screenshot_7](https://user-images.githubusercontent.com/18325407/192984879-d286bbfb-c963-4ab0-8d5d-a604544281f7.png)
![Screenshot_8](https://user-images.githubusercontent.com/18325407/192984882-5e51845b-9e18-4792-ba2e-5cb6585599a1.png)

The reason is that in the logo link it uses http while I work on https.

### Steps to replicate

On https environment upload a logo on "customize backend" section of wintercms.

**Comment by LukeTowers** [comment]
@haralake this has never been a problem before, are you using Cloudflare or have you customized what the `app.url` is or have you customized what the `cms.storage.uploads.path` config value is?

If you're using Cloudflare, try using the new [Winter.Cloudflare plugin](https://github.com/wintercms/wn-cloudflare-plugin)

**Comment by haralake** [comment]
Yes i'm using Cloudflare. For some strange reason suddenly the problem was solved. I can't figure out what the problem was.

**Comment by LukeTowers** [comment]
Could have been a delay in Cloudflare issuing certs for you if you're using their flexible SSL.
