### ISSUE TITLE
Test content file exists

### ISSUE THREAD

**Issue by m-paniez9292** [wintercms/winter#731]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Pages

### Issue description

Hi,
I would like, in a CMS partial, test if a content file exists.
So I do :
```
                {% if content(<my_file.htm>) %}
                  {% content <my_file.htm> %}
                {% else %}
                  <something else>
                {% endif %}
```
If I do that, I have a twig error on my if line : `An exception has been thrown during the rendering of a template ("The content file '<my_URL>' is not found.").`

How can I do that ?

Thanks

### Steps to replicate

After a fresh install, just add the test

**Comment by mjauvin** [comment]
Just do the test in your page/component code section and add a boolean page variable that make that result available in your twig markup.

**Comment by m-paniez9292** [comment]
Re,

Sorry if you re-write the same.

My layout is
```
....
    {% partial "site/content" %}
....
```
So, in my partial site/content, I have :
```
...
    {% if content(<my_file.htm>) %}
      {% content <my_file.htm> %}
    {% else %}
      <something else>
    {% endif %}
....
```
So, I don't have page file between layout and this partial.

Thanks

**Comment by mjauvin** [comment]
Same, just use the layout code section.

**Comment by m-paniez9292** [comment]
Re,

I modify my layout to :
```
....
    {% set hasContent=false %}
    {% if content(<my_file.htm>) %}
        {% set hasContent=true %}
    {% endif %}
    {% partial "site/content" hasContent=hasContent %}
....
```
I have the same error.
EDIT : the error is always on test (so now in the layout file)

Thanks

**Comment by mjauvin** [comment]
This is how it should look in your layout file:
```
description = "default layout"
==
function onInit()
{
    $this['contentPartial'] = \Cms\Classes\Partial::loadCached($this->controller->getTheme(), 'my_file');
}
==
{% if contentPartial %}
  <h1>Hello World!</h1>
{% else %}
  <h1>Sorry...</h1>
{% endif %}
```

**Comment by m-paniez9292** [comment]
Re,
With that method, it works.
Just, the same method to call partial works fine (ie. `{% if partial(<my_file.htm>) %}` ).
Thanks

**Comment by mjauvin** [comment]
Oh, I see your point now... the `partial()` twig function returns false if the partial is not found, but the `content()` twig function throws an exception if the content file does not exist.

ref. https://github.com/wintercms/winter/blob/develop/modules/cms/classes/Controller.php#L1129-L1131

@LukeTowers @bennothommo should we change this behavior?

**Comment by m-paniez9292** [comment]
Re,

> Oh, I see your point now... the `partial()` twig function returns false if the partial is not found, but the `content()` twig function throws an exception if the content file does not exist.

I can't say better than you. Sorry if my explanation was bad or not clearly explicit.
Thanks

**Comment by bennothommo** [comment]
@mjauvin I'd say it makes sense for it to return `false`, so that people can use a conditional to display fallback content like with a partial.
