### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long |  WinterCMS  1.2.1

### ISSUE THREAD

**Issue by GaneshKandu** [wintercms/winter#735]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

no

### Issue description

I am getting this error on "Installing Winter CMS" "Installation" step

Unable to run migrations. SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `sessions` add unique `sessions_id_unique`(`id`))

### Steps to replicate

Installing similarly as here mentioned. but getting error on "installation" step

### Workaround

I am installing WinterCMS on mysql 5.5 
and tested on 5.6 and 5.7 also and its not working on 5.6
its working on 5.7.

**Comment by LukeTowers** [comment]
Minimum supported MySQL version is currently 5.7 for Winter v1.2. See https://github.com/wintercms/meta/blob/master/l9-upgrade-notes.md#database-servers
