### ISSUE TITLE
Repeater field not initialzed properly pivot modal

### ISSUE THREAD

**Issue by hirisov** [wintercms/winter#741]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Test

### Issue description

If there is a relation widget with pivot model with a repeater type field, then in the pivot modal the repeater is always empty. If I enter some data to it and save it, the data is properly updated in the database, but upon opening the pivot modal the repeater is stil empty.

### Steps to replicate

Please see this PR: https://github.com/wintercms/wn-test-plugin/pull/11

**Comment by mjauvin** [comment]
I was able to "patch" this by adding the following method to the Repeater widget class, but I feel this isn't right:
```
public function getLoadValue()
{
    if ($this->formField->value !== null) {
        return is_array($this->formField->value) ? $this->formField->value : json_decode($this->formField->value);
    }

    return parent::getLoadValue();
}   
```

**Comment by hirisov** [comment]
@mjauvin almost 3 months passed, would it be possible to merge your solution until there is a more robust fix available? I know this is not the final solution, but at least it works for now. It kinda clutters CI/CD workflows that we have to manually patch this file now to get it work :(

**Comment by mjauvin** [comment]
Can you check if dynamically adding the method in one of your plugin's boot method like this works?
```
\Backend\FormWidgets\Repeater::extend(function ($widget) {
    $widget->addDynamicMethod('getLoadValue', function () use ($widget) {
        if ($widget->formField->value !== null) { 
            return is_array($widget->formField->value) ? $widget->formField->value : json_decode($widget->formField->value);
        }       
 
        return parent::getLoadValue();
    });
});
```

**Comment by hirisov** [comment]
Unfortunatelly it doesn't work, the getLoadValue defined this way is never called. I added this to the boot method:

```
    /**
     * Boot method, called right before the request route.
     */
    public function boot(): void
    {
        \Log::debug('extending Repeater FormWidget');
        \Backend\FormWidgets\Repeater::extend(function ($widget) {
            $widget->addDynamicMethod('getLoadValue', function () use ($widget) {
                \Log::debug('inside getLoadValue');
                \Log::debug($widget->formField);
                if ($widget->formField->value !== null) { 
                    return is_array($widget->formField->value) ? $widget->formField->value : json_decode($widget->formField->value);
                }       
        
                return parent::getLoadValue();
            });
        });
    }
```

in `system.log` I only can see this line:

```
[2023-01-26 09:41:35] development.DEBUG: extending Repeater FormWidget 
```

**Comment by mjauvin** [comment]
> I was able to "patch" this by adding the following method to the Repeater widget class, but I feel this isn't right:
> 
> ```
> public function getLoadValue()
> {
>     if ($this->formField->value !== null) {
>         return is_array($this->formField->value) ? $this->formField->value : json_decode($this->formField->value);
>     }
> 
>     return parent::getLoadValue();
> }   
> ```

@LukeTowers opinion on this fix?

**Comment by LukeTowers** [comment]
@hirisov is this still an issue? Ping me if so and I'll take another look.

**Comment by hirisov** [comment]
@LukeTowers yes this issue is still present with dev-develop branch of WinterCMS (I could reproduce with a fresh install and the test plugin, with the steps I described above). If I add the getLoadValue() manually to `modules/backend/formwidgets/Repeater.php` then that seems to fix the problem.

**Comment by mjauvin** [comment]
@bennothommo @LukeTowers this got reported before and got closed by the system.
