### ISSUE TITLE
[MediaManager] >_ link to rename / delete

### ISSUE THREAD

**Issue by m-paniez9292** [wintercms/winter#753]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Pages

### Issue description

Hi,
In MediaManager, I create a directory and upload a picture in it.
When I click on ">_" on the line of the file (to rename or delete the file), I have this error :
`"Backend\Widgets\MediaManager::onLoadRenamePopup(): Return value must be of type array, string returned" on line 367 of /home/www/xxxxxx/www/modules/backend/widgets/MediaManager.php`

Thanks

### Steps to replicate

After an install, I begin to make a website and, at a moment, I use mediaManager to rename a picture in a subdirectory.

**Comment by LukeTowers** [comment]
Update to 1.2.1, this was fixed 3 months ago in https://github.com/wintercms/winter/commit/b8046c222805f566acc54f63a7db7053cb4da300
