### ISSUE TITLE
Date shown incorrectly after opening edition mode on a record

### ISSUE THREAD

**Issue by RoKrypto** [wintercms/winter#757]
### Winter CMS Build

1.1

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

I use Winter 1.1.9 and PHP 7.4.32. I have a model called Promotions. The logic behind it is to show promotions in detail within a range of dates. Among the input fields, there are 2 date fields oriented to define said range. Let's call these "From" and "To". After creating a couple of records (or promotions), I go back to one of them to change the range of dates. Before I retouch anything, I realized the dates shown were from one day before.

Nevertheless, the dates display correctly in the list of promotions and in the database. This weird issue only takes place if I want to edit a record (or promotion), that is when I open a record, which takes me to the form to edit it.

### Steps to replicate

Let's suppose I set Promo A to be valid from Nov 6th to Nov 25th. Then, I decide to change something from Promo A so I go to its record. I'm taken to the form to edit it and the dates retrieved end up being Nov 5th and Nov 24th.

**Comment by LukeTowers** [comment]
Try setting `ignoreTimezone: true` on your date fields in your `fields.yaml` file.

**Comment by RoKrypto** [comment]
It worked. Thank you so much, @LukeTowers
