### ISSUE TITLE
.fancy-layout class breaks nested forms in tabs

### ISSUE THREAD

**Issue by der-On** [wintercms/winter#758]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

wn-pages

### Issue description

When a form uses the `.fancy-layout` class like the static page forms do, nested forms inherit the styles of the fancy-layout making them look strange. In addition the collapse/expand icons of the nested forms do not work properly, as nested forms can no longer be expanded.

![Bildschirmfoto am 2022-11-07 um 14 09 22-fullpage](https://user-images.githubusercontent.com/359399/200319834-e28162a1-fe4d-4f49-9c5c-342413a0a845.png)

### Steps to replicate

Programatically add a tab field to a static page form from with a plugins register method:

```php
Event::listen('backend.form.extendFields', function($widget) {
  if ($widget->isNested) { return; }
  $widget->addTabFields([
    'nested' => [
      'type' => 'nestedform',
    ],
  ]);
}
```
The nested form appears with a background and cannot be expanded once collapsed.

### Workaround

Create a custom css and inject it into the backend page, that resets all the custom styling of the nested forms. This however will not fix the broken collapse/expand icon.

**Comment by bennothommo** [comment]
If you move the fields to the primary or secondary tabs, the nested form works better in the fancy layout. I do it that way quite often. The fields you have in your screenshot are being added as "outside" fields.

**Comment by der-On** [comment]
@bennothommo This works but adds an additional row of tabs which clutters things up.

**Comment by bennothommo** [comment]
The only other option would be to make a PR to the [`fancylayout.less`](https://github.com/wintercms/winter/blob/develop/modules/backend/assets/less/layout/fancylayout.less) to make its styling more targeted to just the "main" instance of the form. You'll also need to make adjustments to the custom backend styling functionality that allows people to re-colour the backend, as I believe that uses the same CSS selectors.

**Comment by der-On** [comment]
@bennothommo I will take a look into that.

**Comment by bennothommo** [comment]
@der-On could you give #763 a test and let me know if that fixes it for you? :)

**Comment by der-On** [comment]
@bennothommo It helps. But the problem with the collapse/expand button still persists. It is now clickable but toggles both the nested form and the form with orange background on top.

![Bildschirmfoto am 2022-11-10 um 21 06 51-fullpage](https://user-images.githubusercontent.com/359399/201195419-6601fb12-a54b-47fa-b809-4596c3801d00.png)

With the tailwind-ui backend plugin the nested form still has an orange-background.

![Bildschirmfoto am 2022-11-10 um 21 09 18-fullpage](https://user-images.githubusercontent.com/359399/201195708-26e9b489-c05d-41d5-8eb7-c212b354b7d5.png)

**Comment by bennothommo** [comment]
@der-On at the moment I'm just making sure it works with the vanilla UI. Once that's done, we'll fix up the Tailwind UI plugin.

I'll check the collapsible functionality. I'm fairly sure it works in the CMS area, so it should work here too.

**Comment by bennothommo** [comment]
Sorry, forgot to mention about the collapsible functionality of the nested forms - I don't believe we intend to make these collapsible. A nested form is just a way of collating reusable sets of fields. So it'll be a case of removing the collapsible arrow for the nested fields.

**Comment by bennothommo** [comment]
One more thing - you will need to re-save the Brand Settings in the Backend if you've used that functionality previously, as it needs to recompile the selectors for the brand settings.
