### ISSUE TITLE
Not working translation in properties ReportWidget

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#770]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

WebVPF.Packagist

### Issue description

Translation does not work in properties with dropdown type.

https://github.com/WebVPF/wn-packagist-plugin/blob/bfcb655ac087999cb30d6b9b911f26c4ad7e4960/reportwidgets/Vendor.php#L20

### Steps to replicate

Install plugin:

```bash
composer require webvpf/wn-packagist-plugin
```

Add a ReportWidget **Packagist Vendor**. See the dropdown lists in the widget settings.

![2022-11-19_181253](https://user-images.githubusercontent.com/61043464/202861176-01036642-e351-4239-8792-0296f921dc85.jpg)

**Comment by LukeTowers** [comment]
@WebVPF just wrap them in calls to `Lang::get()` for now
