### ISSUE TITLE
Fancy layout styling

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#773]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Test

### Issue description

PR #763 introduce degenerative styles when using nested forms under repeater fields.

### winter/wn-backend-module 1.2.1
![image](https://user-images.githubusercontent.com/282242/203379877-63e81c06-d3aa-4960-b5cb-ad2d47eb0490.png)

### winter/wn-backend-module dev-develop 8972c89
![image](https://user-images.githubusercontent.com/282242/203380513-ead7e01e-66c6-4070-a98a-9869c7847b98.png)

**Lost padding:**

Tab panes have lost their inner padding.
![image](https://user-images.githubusercontent.com/282242/203390977-6c149cb7-4dd9-4516-b19b-ffef0e0b884b.png)

**Extras chevron:**

![image](https://user-images.githubusercontent.com/282242/203387393-74c445f3-8821-42a2-ab04-d7408a6da837.png)

The extra `right chevron` seems to come from: 
https://github.com/wintercms/winter/blob/develop/modules/system/assets/ui/storm.css#L1226
```css
.control-tabs.scroll-after::after {
  display: block;
}
```

**Note:**
On my screenshots, the repeated section fields have a dedicated `small-panels` class added which allows me to remove the unnecessary padding.
```css
.small-panels .field-repeater li.field-repeater-item {
  padding: 0 !important;
}
```

### Steps to replicate

 - Install Winter
 - Install this fork/commit of Winter.Test plugin to have the complex field for page model https://github.com/damsfx/wn-test-plugin/commit/d4b773f064f87363f5364194fa65f25d8565b873 
 - Go to backend to edit the complex page

**Comment by LukeTowers** [comment]
@damsfx are you able to add a test case for this in the Test plugin under the Record model's fields.yaml? We're using it as a kitchen-sink testing area for every widget & field and complex cases like these that could cause issues.

**Comment by LukeTowers** [comment]
<img width="634" alt="Screenshot 2023-05-29 at 2 59 41 PM" src="https://github.com/wintercms/winter/assets/7253840/cb480fae-4665-437a-adab-2a53bb44aedc">
