### ISSUE TITLE
Support for 2FA on the backend login page

### ISSUE THREAD

**Issue by hirisov** [wintercms/winter#775]
### Discussed in https://github.com/wintercms/winter/discussions/774

<div type='discussions-op-text'>

<sup>Originally posted by **hirisov** November 24, 2022</sup>
It would be nice to have 2FA option for the backend athentication for increased security.

There is an existing plugin for OctoberCMS for that:

https://octobercms.com/plugin/vdlp-twofactorauthentication

but the developers are only interesed in supporting OctoberCMS, so they will not make this plugin available for WinterCMS, and I think this should be a nice core feature anyway.</div>

**Comment by LukeTowers** [comment]
There's no need for a discussion and an issue.
