### ISSUE TITLE
Fallback getAttribute to Eloquent Model

### ISSUE THREAD

**Issue by Xaero** [wintercms/winter#776]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When using casts that resolve to a class, f.e. when using https://github.com/spatie/laravel-schemaless-attributes, Winter does not work due lack of support in the getAttribute method in the Model class. 

Would it be possible to fall back to the Eloquents getAttribute method, when the 'normal' behaviour of Winters getAttribute do not suffice?

### Steps to replicate

-

### Workaround

Override the getAttribute method per model 

```
 public function getAttribute($key)
    {
        return parent::getAttribute($key) ?? EloquentModel::getAttribute($key);
    }
```

**Comment by LukeTowers** [comment]
Thanks for the report @Xaero, should be fixed in https://github.com/wintercms/storm/commit/79ab8a906cd1851af5e1731879902f4a604351ea
