### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by christiantosta** [wintercms/winter#788]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

PostgreSQL

### Issue description

When I click on any backend link that uses FileUpload formwidget, I faced the following error:

"A non-numeric value encountered" on line 531 of /srv/www/wintercms/sites/catalvimv/web/modules/backend/formwidgets/FileUpload.php

### Steps to replicate

1. Install wintercms using compose 
2. Access a backend link that have file upload widget

### Workaround

Patch follows:
```
--- modules/backend/formwidgets/FileUpload.php~   2022-10-13 06:35:23.000000000 -0300
+++ modules/backend/formwidgets/FileUpload.php   2022-11-25 02:03:09.833614382 -0300
@@ -528,6 +528,6 @@
                 $size = $match[1] * pow(1024, $pos + 1);
             }
         }
-        return floor($size / 1024 / 1024);
+        return floor((double) $size / 1024 / 1024);
     }
 }
```

**Comment by christiantosta** [comment]
Any follow up?

**Comment by bennothommo** [comment]
@christiantosta I'm more curious as to the circumstances that the `$size` variable is not a numeric value. Is it happening for a particular file? Or is it every file?

While your fix would work, it's simply coercing the $size to a number, and not exactly fixing the root cause of the issue.

**Comment by christiantosta** [comment]
I don't know about circumstances that the $size is not a numeric value, but my client is using patched version for about 7 months for now without that error. So this little change, in addition to fix the problem, doesn't hurt.

**Comment by bennothommo** [comment]
@christiantosta the method in question reads the PHP `upload_max_filesize` config. What's the configuration value that your client is using?

**Comment by christiantosta** [comment]
php_value[upload_max_filesize] = 50m

**Comment by bennothommo** [comment]
@christiantosta ah, so it's a case sensitivity issue with the lower-case `m` for megabytes. https://github.com/wintercms/winter/commit/02cbd8654ac98145ea64bfa410b9c0867caf4bbd should fix this.
