### ISSUE TITLE
The "name" argument does not exist (Winter.Drivers)

### ISSUE THREAD

**Issue by Webmasters-WPNGO** [wintercms/winter#803]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

SQLite

### Plugins installed

Winter.Drivers

### Issue description

Symfony\Component\Console\Exception\InvalidArgumentException: The "name" argument does not exist. in .../vendor/symfony/console/Input/ArrayInput.php:188

### Steps to replicate

Updated to version 1.2.1. I do the installation:
Customize advanced options? (yes/no) [no]:
yes
...
Install the Winter.Drivers plugin? (yes/no) [no]:
yes
...
The "name" argument does not exist.

**Comment by LukeTowers** [comment]
Out of curiosity, what are you installing the Winter.Drivers plugin for?

**Comment by Webmasters-WPNGO** [comment]
> Out of curiosity, what are you installing the Winter.Drivers plugin for?

To be honest, this is my first time installing Winter and I decided to install everything that the installer offers for testing :)

**Comment by LukeTowers** [comment]
Fixed by https://github.com/wintercms/winter/commit/ffa6f99210234f86891def675df69341d30f925c
