### ISSUE TITLE
Install on Debian

### ISSUE THREAD

**Issue by ghost** [wintercms/winter#81]
Hello dear Team,
Could it be possible to install the same as way below and get an install-master folder ? Currently empty 
wget https://codeload.github.com/wintercms/install/zip/master -O wintercms.zip

Wish you all the best to come

Best regards

**Comment by bachvtuan** [comment]
You can try install by download release version. Here is latest https://github.com/wintercms/winter/archive/refs/tags/v1.1.2.zip

**Comment by ghost** [comment]
Hello, thanks for this reply,
I'm feeling sorry because I'm a non-technical user, 
this is the way I used to install in the past with an install.php file inside the folder, similar to the one below, I'm hoping it could be done soon.
https://codeload.github.com/octobercms/install/zip/master

Cordially
