### ISSUE TITLE
Wintercms `storm/src/Support/ClassLoader.php` doesn't allow all lowercase namespace vendor packages to be autoloaded

### ISSUE THREAD

**Issue by sugarcanehyena** [wintercms/winter#816]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

n/a

### Issue description

Have tested this in wintercms 1.2.1

When loading several vendor packages in a custom plugin. Wintercms can only load the Capitalized namespace vendor packages and can't handle lowercased namespace vendor packages!

This issue only started after wintercms upgraded from Laravel 5 LTS to Laravel 9 LTS. However `storm/src/Support/ClassLoader.php` should allow lower case namespace vendor packages to be auto-discovered.

Have had long talks with several people working at php, psr and laravel and they all agree that wintercms should load lowercase namespace vendor packages.

Have opened this issue here as the `Storm` repo doesn't have a `issue` tab displaying.

### Steps to replicate

Namespace vendor package examples:

### Working

```
use Acme\Example\ThisIsAnExample
```

The vendor package composer file would be like this:

```json
    "autoload": {
        "psr-4": {
            "Acme\\": "src/acme/"
        }
    },
```

### Not Working

```
use acme\example\ThisIsAnExample
```

The vendor package composer file would be like this:

```json
    "autoload": {
        "psr-4": {
            "acme\\": "src/acme/"
        }
    },
```

Note the `acme` and `example` are lowercase.

**This is a problem that was brought over fromthe  octobercms hardfork and found here**:
https://github.com/octobercms/library/blob/3.x/src/Support/ClassLoader.php

Wintercms file issue is found here:
https://github.com/wintercms/storm/blob/develop/src/Support/ClassLoader.php

## Stack Trace of Issue

![image](https://user-images.githubusercontent.com/75955182/211205554-4a0049f6-79e0-40b3-a0e2-324d78ae2480.png)

```
67 | require_once() | ~/vendor/winter/storm/src/Support/ClassLoader.php | 101
66 | Winter\Storm\Support\ClassLoader->load(…) | ~/vendor/winter/storm/src/Support/ClassLoader.php | 199
```

### Workaround

A workaround would be for the vendor package to Capitalized their namespaces. However, the vendor package has over 1 million installs and used by 795K. Therefore the owners and people at Laravel and php using the vendor package are not happy to change their namespace vendor package and everyone says it's a wintercms issue! PSR say wintercms is wrong and should allow lowercase namespace vendor package auto-discovery.

**Comment by LukeTowers** [comment]
@sugarcanehyena the ClassLoader is meant for autoloading Winter CMS plugin classes that are not managed by Composer. If the package you are using is being pulled in via composer and has the following in their composer.json file, then it should be loading fine. You might need to try running `composer dump-autoload`?

```json
"autoload": {
        "psr-4": {
            "Acme\\": "src/acme/"
        }
    },
```

It would be extremely helpful if you could provide specific details in your report as to what specific package is causing you issues and the exact order of steps you took to include it in your Winter project so that we can replicate them using a fresh install of Winter to figure out what is causing the issue for you.

**Comment by sugarcanehyena** [comment]
We first noticed the error on a production server (after upgrading), then tested it on xampp on a fresh install.

I'll code a small plugin to demo the issue and post the link here in the next 48 hours, for you to try and replicate on a fresh install.

**Comment by sugarcanehyena** [comment]
@LukeTowers 

I've done multiple testing on many fresh new installs and the bug/issue seems to be gone now. I've not updated the plugin code and always used cms version 1.2.1 and php 8.2.0 with all the tests. My only guess is that a third-party vendor package has been updated and fixed the issue? 

Is it possible to close this issue and if I come across the issue in the near (and I can replicate it on a fresh installation), then you could re-open this issue.

**Comment by LukeTowers** [comment]
Sounds good @sugarcanehyena. We definitely want to make sure our ClassLoader works correctly but without reproduction instructions it doesn't seem like there's anything else we can do at the moment.
