### ISSUE TITLE
<script> tags in report widget templates are not executed when dashboard loads

### ISSUE THREAD

**Issue by hirisov** [wintercms/winter#817]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

If there is a <script> tag in the template of a report widget, and that report widget is added to the dashboard, then the scipt is not executed. This was working fine in October CMS 472.

If the script is moved to an external JS file and added in the loadAssets() of the report widget, then it cannot interact with the DOM elements defined in the template, as at the time of the asset loading and executing the partial is not loaded yet.

So there is no working way currently to use JS in a report widget which interacts with the DOM elements defined in the template.

### Steps to replicate

Create a report widget with this template:

```
<div class="report-widget">
    <div id="test">before script run</div>
</div>

<script>
    const testElement = document.getElementById("test");
    testElement.innerHTML = 'after script run';
</script>
```
then add this report widget to the dashboard.

Upon visiting the dashboard the widget's content should be "after script run", but instead it stays "before script run". If the user opens the properties panel of the report widget by clicking on the cogwheel icon and then closes it (without changing anything), then the content changes to "after script run".

### Workaround

If the user opens the properties panel of the report widget by clicking on the cogwheel icon and then closes it (without changing anything), the script defined in the <script> runs.

**Comment by ericp-mrel** [comment]
Have you tried using an event listener so the script waits until the DOM has been rendered before trying to modify DOM elements?

Something like:
```js
document.addEventListener('DOMContentLoaded', () => {
    // your code here...
    const testElement = document.getElementById("test");
    testElement.innerHTML = 'after script run';
});
```

**Comment by hirisov** [comment]
It is still the same that way if I use in the template. Even if I put a single `console.log()` there, that will not run either - so nothing runs which is defined inside the template file <script> tag.

I tried to put that into the external JS and load it via loadAssets(), but still the div#test does not exists when it runs and I get javascript error:

`Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')`
