### ISSUE TITLE
Cache while using incognito browser is not working

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#819]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

I have a `Cache::remember` function which I want to use to do some cleaning, basically like a cronjob.
I woud like to think it works great, but while testing some other functionality in incognito browser, I noticed that the Log is spammed with 'Monthly Maintenance'

So it's running the maintenance on every page refresh?
```
public function boot() {

    // delete data after period of X time
    Cache::remember('monthly_maintenance', Carbon::now()->addMonths(1), function () {
        Log::info('Monthly Maintenance');
        // ...
    });

}
```
![image](https://user-images.githubusercontent.com/89913092/212034842-62cd96d8-9d27-4986-926c-92102554615f.png)

### Steps to replicate

Use (Chrome) incognito
I'm also using the default file cache driver

### Workaround
Perhaps placing this functionality behind a button on the dashboard with a new widget?

**Comment by LukeTowers** [comment]
Hmm, that's odd behaviour, are you able to replicate that on a fresh install? I think the cache might get cleared on logging in to the backend, although that might have been changed recently.

**Comment by AIC-BV** [comment]
@LukeTowers Something weird must've happened. It seems to be working fine again. 🤷‍♂️
