### ISSUE TITLE
No configuration / routes after artisan optimize / config:cache / route:cache

### ISSUE THREAD

**Issue by ArturCiolkiewicz** [wintercms/winter#839]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Demo

### Issue description

Hello, after running the artisan optimize or config:cache command, the configuration becomes inaccessible to cms. 

The situation occurs both after installation by composer and web installer. Regardless of whether we have configuration in .env or without .env.

It seems that the configuration and routing cache cannot be started. To restore the CMS operation, delete the cache /storage/framework/*.php files

Winter CMS build 1.2.1. (dev-develop too)
PHP 8.1.15
Installed plugins: Winter.Demo 
Fresh install

![image](https://user-images.githubusercontent.com/110459342/219151552-b705ceb5-b217-4c75-9ccf-34e4ac0a133a.png)

### Steps to replicate

- Fresh install (composer / web installer)
- php artisan optimize

**Comment by bennothommo** [comment]
@ArturCiolkiewicz sorry for the delay in responding.

This has been fixed in https://github.com/wintercms/storm/pull/110 and will be released with Winter 1.2.2. If you need the fix in the mean time and are using Composer, you can set Winter and the modules to `dev-develop` to get the latest fixes.
