### ISSUE TITLE
Trigger events not working in preview mode

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#845]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate, Winter.Redirects, Aic.Globals, Aic.ExtendWinterPages, Aic.Blog, Aic.Team, Aic.Account, Aic.Contact, Aic.Invoice, Aic.Discount, Aic.Aftersales, Aic.Reviews, Aic.Faq, StudioBosco.BackendNotifications, StudioBosco.BackendComments, ...

### Issue description

[Trigger events](https://wintercms.com/docs/backend/forms#field-trigger-events) don't seem to happen in preview mode, only in update.

Meaning the fields with `action: hide` are shown in preview
And the fields with `action: show` are hidden in preview

### Steps to replicate

Add trigger event and preview context

### Workaround

Not using preview context

**Comment by bennothommo** [comment]
Re-opening per https://github.com/wintercms/winter/pull/905#issuecomment-1552354735.

**Comment by mjauvin** [comment]
> Re-opening per [#905 (comment)](https://github.com/wintercms/winter/pull/905#issuecomment-1552354735).

fixed in #907
