### ISSUE TITLE
Theme Localisation not working in dev-branch

### ISSUE THREAD

**Issue by xitara** [wintercms/winter#859]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

The theme localisation works in 1.2.1 but not in dev-develop with the same theme

Screenshot from 1.2.1
![Bildschirmfoto_2023-03-05_15-02-40](https://user-images.githubusercontent.com/26457767/222965391-b4b249a5-a8cd-4583-91e4-ad0aaf518ce6.png)

Screenshot dev-develop
![Bildschirmfoto_2023-03-05_15-02-52](https://user-images.githubusercontent.com/26457767/222965423-be6de333-a820-4bae-9a7e-63e9b678ec97.png)

Theme-folder and theme-code is identical. The only difference: 1.2.1 runs on php 8.1 and dev-develop on php 8.0

### Steps to replicate

-

**Comment by LukeTowers** [comment]
Hmm, not sure why that wouldn't be working. Are you able to test it out with some debugging statements to see what's going wrong? 

The logic gets kicked off at https://github.com/wintercms/winter/blob/develop/modules/cms/classes/Theme.php#L74-L76 and is executed here: https://github.com/wintercms/winter/blob/develop/modules/cms/classes/Theme.php#L579.

https://github.com/wintercms/winter/blob/develop/modules/cms/controllers/ThemeOptions.php#L138 should be running before the fields are rendered.

I'm guessing the recent Child Theme feature changes probably introduced the issue but not sure what it is at the moment.

**Comment by xitara** [comment]
I'll test it out tomorrow :)

**Comment by WebVPF** [comment]
@xitara Do you have the DarkBackend plugin installed?

**Comment by xitara** [comment]
@WebVPF I use dark reader extension in chrome.
I'm working on a darkmode plugin that looks similar, but it  isn't ready now

**Comment by WebVPF** [comment]
@xitara I'm sorry. I thought you had an older version of the DarkBackend plugin installed. Once the styles were similar.
Thought you need to reinstall plugin.
Here are screenshots of the plugin: https://github.com/WebVPF/wn-darkbackend-plugin/issues/6

**Comment by xitara** [comment]
I'll take a look :)

**Comment by LukeTowers** [comment]
@xitara you could also give the TailwindUI skin a try, it's got darkmode support (https://github.com/wintercms/wn-tailwindui-plugin)

**Comment by xitara** [comment]
@LukeTowers I got it.
The themes. prefix was missung. Sent a pull request
