### ISSUE TITLE
Cannot detect new seeder

### ISSUE THREAD

**Issue by chammeow** [wintercms/winter#868]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Created new seeder under backend > database > seeds. Cannot detect new seeder

### Steps to replicate

1. Created new seeder under backend > database > seeds
2. Run cmd php artisan winter:up > Cannot detect new seeder.
3. Try running php artisan db:seed > shows  ERROR  There are no commands defined in the "db" namespace.

**Comment by bennothommo** [comment]
@chammeow is this the Builder plugin you created the seeder in?

**Comment by LukeTowers** [comment]
@chammeow seeders and migrations in Winter plugins are run the same way, either with `winter:up` or `migrate`. There is no separate `db:seed` command in Winter.
