### ISSUE TITLE
Using assets combiner broke url(...) 

### ISSUE THREAD

**Issue by damsfx** [wintercms/winter#895]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

none

### Issue description

When using assets combiner : 
```twig
{{ [
    'assets/css/vendor.css',
    'assets/css/theme.css'
]|theme }}
```
If one of the assets contain a reference to a file with `url(...)` the reference get corrupted with backslash instead of slash.

**This issue was detected on a Windows platform**, which may be important given the difference in the use of slashes and backslashes.

### Steps to replicate

In the demo theme, change :
```twig
<link href="{{ 'assets/css/vendor.css'|theme }}" rel="stylesheet">
<link href="{{ 'assets/css/theme.css'|theme }}" rel="stylesheet">
```
to :
```twig
<link href="{{ [
    'assets/css/vendor.css',
    'assets/css/theme.css'
]|theme }}" rel="stylesheet">
```
Reload site in FrontEnd, the Winter logo ha gone.

The reference to the link in the class definition is change  
from : `background-image: url('../images/winter.png');`  
to : `background-image: url('../themes\demo\assets/images/winter.png');`

What it is expected : `background-image: url('../themes/demo/assets/images/winter.png');`

**Comment by jaxwilko** [comment]
@damsfx could you try https://github.com/wintercms/winter/pull/898 and see if that resolves the issue?

**Comment by damsfx** [comment]
> @damsfx could you try #898 and see if that resolves the issue?

@jaxwilko Not suffisent for me.

 * Before : `background-image: url('../themes\demo\assets/images/winter.png');`
 * After : `background-image: url('../themes\demo/assets/images/winter.png');`
 
 The relative link to the asset still have a backslash between themes directory and the theme name.

**Comment by jaxwilko** [comment]
@damsfx thanks, just spent the last hour trying to get a windows VM set up to test on. I've pushed another commit that should fix the issue, but wont be able to test till this VM is set up

**Comment by damsfx** [comment]
@jaxwilko The issue no longer exists.  
Note I'm not testing it on child themes.  
Thank's.

If there is a need to do other tests under Windows, do not hesitate, I always have a machine dedicated to this task with the latest dev-develop version installed.

**Comment by jaxwilko** [comment]
@damsfx thank you very much for your efforts!
