### ISSUE TITLE
ThemePHP error

### ISSUE THREAD

**Issue by markcjf** [wintercms/winter#915]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

SQLite

### Plugins installed

None

### Issue description

On successful install everything appears to work correctly as far as viewing is concerned (haven't tried to create pages, partials etc).
Looking for tutorial on creating theme I followed one that said to create new theme from the new theme button in the settings/front-end. On clicking I receive an error as indicated below:

Cms\Classes\Theme::getDirName(): Return value must be of type string, null returned (Browser)
[Sat Jun  3 22:22:41 2023] [::1]:53568 [500]: POST /backend/cms/themes (Terminal)

### Steps to replicate

Install through web installer
log into backend
move to system/../..../themes
select new theme button

ERROR reported

Am able to duplicate the existing demo theme.

**Comment by bennothommo** [comment]
Confirmed.

**Comment by LukeTowers** [comment]
Should be fixed by https://github.com/wintercms/winter/commit/cba5fa7562ad7424aa8b7540aa1e3d1dccdec95e @markcjf, thanks for the report! I also added some extra features.

**Comment by markcjf** [comment]
After first copying and pasting from the 4 files and then downloading from site - nope, I am having the same issue.

I installed through Ammps and mamps with mysql and the the error attached.
I also install through php -S selecting sqlite and got the same error.



￼

**Comment by LukeTowers** [comment]
> I installed through Ammps and mamps with mysql and the the error attached.

Attachments aren't visible in github issue threads, so I don't see what you're talking about.

> I also install through php -S selecting sqlite and got the same error.

I don't know what you mean here, can you provide additional detail?

**Comment by markcjf** [comment]
Ye sorry - I got it sorted by clearing all history as I had a few instances of wintercms installed.

Thanks
Mark
