### ISSUE TITLE
Plugin replacement system doesn't support aliasing permissions yet

### ISSUE THREAD

**Issue by joaocosta-azores** [wintercms/winter#918]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Fw.EditMe, Winter.Builder, Winter.Pages, Winter.Translate

### Issue description

Plugin replacement system is not handling permission for `Rainlab.Translate`.
Using `BackendAuth::getUser()->hasAccess('rainlab.translate.manage_messages');` in a component  to check whether a user has permissions or not, will return null.

### Steps to replicate

This problem can be replicated by installing plugin [Edit me](https://github.com/mariavilaro/october-plugin-editme) and using it in front end with a string to translate `{% component 'editme' message='My string to translate' %}`.
Then create a user and set permissions to the user as a publisher and give permissions to Manage Locales and Manage message in Winter Translate plugin it.
User will not be able to edit the translation in front end even having permission to change locales and messages.

**Comment by LukeTowers** [comment]
Will archive for now, next person to run into this can ping me and I'll take a look.
