### ISSUE TITLE
v1.2.2 seems that there is no merger #841

### ISSUE THREAD

**Issue by wpjscc** [wintercms/winter#931]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Issue description

v1.2.2  seems that there is no merger https://github.com/wintercms/winter/pull/841

![image](https://github.com/wintercms/winter/assets/76907477/ac428387-8547-4b8c-9eb7-13104c312787)

### Steps to replicate

hello

**Comment by LukeTowers** [comment]
See https://github.com/wintercms/winter/commit/4ed9b10b4ea1c0ca5b37e66be4275cc9321f5cc3#commitcomment-101538858
