### ISSUE TITLE
Problem with backend when installed in root

### ISSUE THREAD

**Issue by agenciazmark** [wintercms/winter#948]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

SQLite

### Plugins installed

none

### Issue description

After Winter 1.2.2, I am unable to access the backend. I tried installing a fresh instance without any plugins, using only the 'demo' theme, but the problem persists. The issue is that it is trying to access a folder located behind the root of the installation, for which it does not have permission. This problem only occurs with the backend, regardless of whether it was installed using Composer or the web installer.

The server is running Ubuntu 20.04 and PHP 8.1 and 8.2.

![Screenshot](https://github.com/wintercms/winter/assets/77156328/10b5352a-af71-4191-9469-7c6bc8349fba)

### Steps to replicate

- Go to the main folder of the server
- Install a new wintercms with version 1.2.2 or higher
- Try to access the backend link

### Workaround

It works if I create a subfolder in the main folder and put the project inside it. Then, I need to create a redirect in the server configs to open the link without the need to include the /subfolder in the URL.

**Comment by mateusmagen** [comment]
Same error here

**Comment by LukeTowers** [comment]
Can you post the full stack trace? I'm not getting this issue on my instances.

**Comment by agenciazmark** [comment]
Sure, here.

![screencapture-clientedigital-zmark-br-backend-2023-07-19-08_52_50](https://github.com/wintercms/winter/assets/77156328/403f7cce-3dfd-4f16-900b-86e37a437b04)

**Comment by LukeTowers** [comment]
Try applying https://github.com/wintercms/storm/commit/41172a383e3b4ce3893b677652995dcad393949c

I'm not sure why this would suddenly be an issue though, the code has been like this since 2020 (v1.1.0).

**Comment by agenciazmark** [comment]
It worked, thank you.
