### ISSUE TITLE
docker-wintercms - Admin password generation vs. docs

### ISSUE THREAD

**Issue by pablorq** [wintercms/winter#95]
- Winter CMS Build: hiltonbanes/wintercms:build.v1.1.2 
- PHP Version:
- Database Engine: mariadb:10.4 
- Plugins Installed: none 

### Description:

The [Quick Start](https://github.com/mik-p/docker-wintercms#quick-start) says:

> Login to the backend with the username `admin` and password `admin`.

After install it a random password is generated, which is a problem not only because it is not matching the docs but also when using tools like Portainer, where the generated password is not easy to retrieve.

### Steps To Reproduce:

Install WinterCMS with the [docker-compose](https://github.com/mik-p/docker-wintercms#mysql--postgres) file with database support.

Run:
```
$ docker-compose up -d
$ docker-compose exec web php artisan winter:up

...

Winter.Demo
 - v1.0.1:  First version of Demo
Seeded System 
Seeded Backend 

\Backend\Database\Seeds\DatabaseSeeder reported:
 - The following password has been automatically generated for the "admin" account: Tnq1g8Uj45itsKnYIkVC7p
```

Go to the backend page.

Try `admin:admin` as specified on the docs.

It doesn't work.

### Spected Behaviour
Use `admin:admin` as specified on the docs to access the backend.

**Comment by bennothommo** [comment]
@pablorq Please submit an issue to @mik-p to adjust the Docker build. One thing I would suggest he does is set up the build process to run `php artisan winter:passwd` on first entry and set the password from an environment variable (or set it to `admin` / `admin` by default).

**Comment by pablorq** [comment]
I can't (nobody can, really) submit issues to @mik-p on [docker-wintercms](https://github.com/mik-p/docker-wintercms).

This is why I submit it here.

**Comment by mik-p** [comment]
Yes I have used this suggestion previously and can add some ways to fix. For your issue you may also run:
docker exec -it container_name winter passwd admin admin

After container start.

Should be able to make issues now

**Comment by pablorq** [comment]
(Moved to https://github.com/mik-p/docker-wintercms/issues/)
