### ISSUE TITLE
[Enhancement]: Auto guess table name from model namespace

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/winter#960]
Laravel models don't require the table property to be set because they can guess what it is called from the namespace, we should be able to do that as well.

**Comment by mjauvin** [comment]
@LukeTowers do you mean the fact we don't prepend the author & plugin namespace to the table name ?

**Comment by bennothommo** [comment]
Given that the `Model` class is in Storm, including the namespace in the table name resolution there would be placing core  functionality into Storm, so might not be the way to go.

The only way (currently) that I can see us doing this is extending the base `Model` class, perhaps in the System module's service provider, and dynamically adding the `$table` property if it doesn't exist.

**Comment by LukeTowers** [comment]
I was thinking further on this and I think it has the potential to be a breaking change too, given that I think the original Laravel table name guessing logic is in place so if anyone is currently using non-Winter table names with models that don't define their table names we'd run into issues with that.

**Comment by bennothommo** [comment]
@LukeTowers do you mean for models defined outside of Winter (ie. from a package)? I'd suspect that would be a non-issue because they'd be extending Illuminate, not Winter.

**Comment by LukeTowers** [comment]
@bennothommo no I mean if someone has defined the following:

```php
namespace Winter\User\Models\User;

use Winter\Storm\Database\Model;

class User extends Model
{
    // no $table definition
}
```
uses `users` in the current codebase but if we change the base model would point to `winter_user_users`

**Comment by bennothommo** [comment]
Gotcha - yeah I agree, it would be a BC break and I can't think of a way around that, so I think we'll have to leave it as is.
