### ISSUE TITLE
Cannot assign user roles or groups to own user.

### ISSUE THREAD

**Issue by der-On** [wintercms/winter#979]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

I cannot assign user groups or roles to my own account.

### Steps to replicate

I go to Settings > Administrators > and click on my own user account.

I get to the edit form of my account, but cannot assign groups or roles.

If I click on any other user account I can assign groups or roles.

Groups or roles can be used programatically for other things then permissions and it would be good to assign those to own user.

### Workaround

Create another admin user or user with the permission to manage users, login or impoersonate as this user and then edit your own user and assign groups or roles.

**Comment by LukeTowers** [comment]
This is on purpose so a user cannot add more permissions to their own account without jumping through an extra hoop. Suggestions welcome.

**Comment by der-On** [comment]
That is a good thought but maybe for super users we could enable adding roles at least?

**Comment by LukeTowers** [comment]
@der-On I would counter that suggestion with the point that your super user accounts should not be actively used as a working account on the system, they should be "break glass in case of emergency" accounts and your normal working accounts should be non-superusers. This helps ensure that permissions are configured correctly for everyone when devs are limited to non-superuser accounts.

**Comment by der-On** [comment]
Got it and thanks for clarifying.

**Comment by LukeTowers** [comment]
To be clear, I'm not trying to shut down the suggestion, just raising points about why it is the way it currently is. If anyone has other suggestions or points to make on this discussion by all means feel free to continue discussing it.
