### ISSUE TITLE
Nothing to migrate: impossible to update plugins

### ISSUE THREAD

**Issue by AllARTSoftworks** [wintercms/winter#981]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.User, Winter.Translate, Winter.Pages, VojtaSvoboda.TwigExtensions, JanVince.SmallContactForm, Excodus.TranslateExtended, Renatio.DynamicPDF, OFFLINE.Seeder

### Issue description

I just updated Wintercms to the latest version with no issues. 

I tried then to upgrade all the plugins to the latest version but I am unable to do it via 

`php artisan winter:up`

I also tried to install plugins via 

`php artisan plugin:install Author.PluginName `
(i.e.: php artisan plugin:install Winter.Translate) 

but they don't update. 

Here's my plugin list:

+-----------------------------+---------+-----------------+----------------+
| Plugin name                 | Version | Updates enabled | Plugin enabled |
+-----------------------------+---------+-----------------+----------------+
| Winter.User                 | 2.0.0   | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+
| Winter.Translate            | 2.0.0   | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+
| Winter.Pages                | 2.0.0   | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+
| VojtaSvoboda.TwigExtensions | 1.2.7   | No              | No             |
+-----------------------------+---------+-----------------+----------------+
| JanVince.SmallContactForm   | 1.52.1  | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+
| Excodus.TranslateExtended   | 1.0.7   | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+
| Renatio.DynamicPDF          | 4.0.8   | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+
| OFFLINE.Seeder              | 2.1.2   | Yes             | Yes            |
+-----------------------------+---------+-----------------+----------------+

As far as I can tell, they are not updated to the latest version:

**Winter.User** must be **v2.2.0**, mine is **2.0.0**
**Winter.Translate** must be **v.2.1.4**, mine is **2.0.0**
**Winter.Pages** must be **2.1.2**, mine is **2.0.0**
**VojtaSvoboda.TwigExtensions** isn't needed anymore, ok
**JanVince.SmallContactForm** must be **v1.66.0**, mine is **1.52.1**
**Excodus.TranslateExtended** isn't probably needed anymore, ok
**Renatio.DynamicPDF** probably must be updated to **v7.1.0**, mine is **4.0.8**
**OFFLINE.Seeder** must be **3**, mine is **2.1.2**

Any tips on how to update it are very appreciated: thank you in advance. 

### Steps to replicate

php artisan winter:up

**Comment by josephcrowell** [comment]
composer update
then
php artisan winter:up

**Comment by mjauvin** [comment]
If you don't have the plugins in your composer.json file, run `composer require` for each plugin (e.g. `composer require winter/wn-user-plugin`)

**Comment by mjauvin** [comment]
Note: You can find the plugin name used by composer in its own composer.json file.
